### ISSUE TITLE
Adding Grunt build tasks

### ISSUE THREAD

**Issue by Pushplaybang** [AdmitHub/meteor-buildpack-horse#100]
Hey There,

This maybe beyond the scope of your issues, but I'm interested in adding an additional step to the build process, before meteor is built, to optimise extrernal assets, pull in scss libs etc, would I be placing a script in the extra folder?  can I straight install dependancies I require there?  (such as grunt, bower etc?)

and if this is the spot, are there any resources you can point me in the direction of, as I'm quite new to heroku, and haven't dug into buildpacks too much yet.  Thanks!

**Comment by yourcelf** [comment]
The "extras" folder is sourced after the rest of the build finishes.  So if you can do your optimization/etc. after the call to `meteor build` has finished, that would work.  If you need to run these steps before meteor is built, then you'll need to do something else.  You could fork this buildpack and add something to `bin/compile` before the meteor build step to do the extra work.

Heroku buildpacks run as bash scripts, and you can do almost anything supported by a posix shell there.  One of the first steps this buildpack takes is to install nodejs; after that, you could install additional packages like bower/grunt using npm.

**Comment by Pushplaybang** [comment]
@yourcelf  - thanks, yeah I'm already working on a fork, and that's what I suspected for a quick look around.  I'll get stuck in, thanks a lot. :)
