### ISSUE TITLE
Add command "npm config set production" before "npm install"

### ISSUE THREAD

**Issue by tab00** [AdmitHub/meteor-buildpack-horse#103]
To prevent installation of devDependencies in the hosting environment, `npm config set production` should be run before `npm install`.

A Meteor app may have devDependencies when an npm package is added using `npm install --save-dev`, e.g. eslint as shown in The Meteor Guide "Code Style" section: http://guide.meteor.com/code-style.html#eslint-installing

Such packages are not required in a deployed environment and should therefore not be installed in such an environment. `npm config set production` ensures that devDependencies are not installed.

**Comment by jamiecollinson** [comment]
+1

I was just about to raise the same issue as I noticed in the build logs that chimp/selenium-standalone is being installed on my project, despite being declared as `devDependencies`.

**Comment by yourcelf** [comment]
Fixed via #105. Rather than doing a global `npm config set...`, we now use `npm install --production`.
