### ISSUE TITLE
Getting error - The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by zaverichintan** [AdmitHub/meteor-buildpack-horse#107]
remote: ######################################################################## 100.0%
remote:
remote: Meteor 1.3.2.4 has been installed in your home directory (~/.meteor).
remote:
remote: Now you need to do one of the following:
remote:
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack20160531-160-5g28c3/meteor-Efdb/.meteor/packages/meteor-tool/1.3.2_4/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote:
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: -----> Bundling bundle
remote: -----> Checking if this meteor version supports --server-only
remote: -----> Attempting to remove android platform.
remote:
remote:
remote: While removing platforms:
remote: error: android: platform is not in this project
remote:
remote: -----> Moving on.
remote: -----> Building Meteor with ROOT_URL: http://joingravity.com
remote: error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by AdamBrodzinski** [comment]
It sounds like Heroku is not authenticating your correctly. Try this:

http://stackoverflow.com/questions/4269922/permission-denied-publickey-when-deploying-heroku-code-fatal-the-remote-end

**Comment by zaverichintan** [comment]
The issue is that the buildpack is using 3rd party application which takes longer time to load, causing time out.

**Comment by gg2001** [comment]
I had similar issues, and I wrote an article on how to solve it. Check it out: https://medium.com/@gautham.gg/deploy-a-meteor-1-3-application-to-heroku-cda1f68ca20a#.on7al5t2v

**Comment by yourcelf** [comment]
@gg2001 your post says nothing relevant to this issue, and you posted the same comment on multiple issues. Stop that or I'll report your account.

**Comment by zaverichintan** [comment]
This thing is happening as the build pack is using third party application which do not get included on the time of deploying.

**Comment by yourcelf** [comment]
Alright @zaverichintan, sounds like you've figured it out -- I'm going to close this now, but reopen if you think there's a bug with the buildpack.

**Comment by zaverichintan** [comment]
Is it possible to have all the files directly loaded instead of relying on third party server ? Just a thought . Kindly comment your views on this.

**Comment by yourcelf** [comment]
@zaverichintan I don't think I understand the suggestion -- what does "directly loaded" mean in a deployment to a server?  Part of the design of Heroku is that all files will come from *some* third party server.  Using this buildpack, we rely on the following third parties:

 - github: for hosting the buildpack
 - install.meteor.com: for meteor
 - any dependencies meteor requests when it installs -- a whole world of atmosphere, npm, etc. packages.
 - semver.io: for detecting the latest version of node v0.10.x (though we're moving away from this to use meteor's bundled node/npm instead)
 - s3pository.heroku.com: for installing nodejs (though we're moving away from this to use meteor's bundled node/npm instead)
 - any dependencies your app references

Which of these 3rd parties are giving you problems?  I don't believe any of them could be integrated with this buildpack in a reasonable way.
