### ISSUE TITLE
Issue with materializecss dropdowns

### ISSUE THREAD

**Issue by jsantana90** [AdmitHub/meteor-buildpack-horse#113]
Hello there.

I am amaze on how easy it is to deploy to heroku using this package compared to other methods.

I'm having an issue with some css (I think) which doesn't get rendered when I deploy on heroku but it works locally or even when I host it on digitalocean.

My error is the following:

In this picture I'm running it locally:
![screenshot from 2016-06-21 11 14 24](https://cloud.githubusercontent.com/assets/9933887/16235034/59704f9e-37a1-11e6-9cd8-ec53a081c644.png)

This is how it suppose to look.

But this is when I deploy on heroku:
![screenshot from 2016-06-21 11 15 22](https://cloud.githubusercontent.com/assets/9933887/16235060/75a4eabc-37a1-11e6-8372-cfe4f0cadb67.png)

As you can see, the dropdowns aren't appearing.

I'm using Meteor 1.3.2.4 with Angular > 1.5

These are the packages:
https://atmospherejs.com/poetic/materialize-scss
https://github.com/krescruz/angular-materialize

One is installed using atmosphere and angular-materialize is installed using `meteor npm`

What am I doing wrong?

Thanks!

**Comment by yourcelf** [comment]
My best guess: you're using some npm package (angular-materialize?) which is installed locally, but is not included in `package.json`, and so the target doesn't know you need it.

Make sure you install dependencies with `npm install --save <name>` so that they are listed as dependencies in `package.json`.  If that's not it: can you share the repo that has the problem?

**Comment by jsantana90** [comment]
Yes I do have it saved in `package.json` I did a workaround to create a directive in angular which runs a jquery that executes the dropdown styling so each time a `select` with that directive appears the jquery executes correctly which fixed the issue for now.

I could guess this issue is not with this package so I'm closing this for now. Thanks!
