### ISSUE TITLE
FATAL: Can't find meteor app. Set METEOR_APP_DIR...

### ISSUE THREAD

**Issue by tamoyal** [AdmitHub/meteor-buildpack-horse#115]
My `.meteor` dir is in the root of my project so I did not set this env var as recommended but the build pack seems to have trouble recognizing this? Or am I missing something. Here is the verbose output:
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
remote: -----> Node.js app detected
remote: + dirname -- /tmp/buildpack20160628-164-1113pnd/bin/compile
remote: + cd -P -- /tmp/buildpack20160628-164-1113pnd/bin
remote: + cd ..
remote: + pwd -P
remote: + BUILDPACK_DIR=/tmp/buildpack20160628-164-1113pnd
remote: + APP_CHECKOUT_DIR=/tmp/build_8314cc7818ea9fc030eae868581003f8
remote: + APP_SOURCE_DIR=/tmp/build_8314cc7818ea9fc030eae868581003f8
remote: + [ -n ./ ]
remote: + APP_SOURCE_DIR=/tmp/build_8314cc7818ea9fc030eae868581003f8/./
remote: + [ ! -d /tmp/build_8314cc7818ea9fc030eae868581003f8/.//.meteor ]
remote: + [ -d /tmp/build_8314cc7818ea9fc030eae868581003f8/.//app/.meteor ]
remote: + [ ! -d /tmp/build_8314cc7818ea9fc030eae868581003f8/.//.meteor ]
remote: + echo FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' supdirectory.  (Tried /tmp/build_8314cc7818ea9fc030eae868581003f8/./)
remote: FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' supdirectory.  (Tried /tmp/build_8314cc7818ea9fc030eae868581003f8/./)
remote: + exit 1
remote: 
remote:  !     Push rejected, failed to compile Node.js app
```

**Comment by yourcelf** [comment]
Is the `.meteor` directory checked in to git?  It should be.  If you listed .meteor in `.gitignore`, this error will come up.

`.meteor/.gitignore` (managed by meteor) will take care of ignoring any subdirectories that should not be stored in git, but the `.meteor` directory should otherwise not be gitignore'd.

**Comment by tamoyal** [comment]
That wasn't the problem but it did turn out to be project specific. I missed something stupid - closing this out

**Comment by armostafizi** [comment]
@tamoyal Hey, do you happen to remember what the issue was? I'm having the same problem. Thanks.

**Comment by tamoyal** [comment]
@armostafizi Sorry man I don't but based on my comment it was _really_ stupid so just poke around for any obvious misconfigurations. I guess a reminder that I should be specific about the resolution regardless as it may help people. Sorry!

**Comment by pihyper** [comment]
Facing the same issue even though my .meteor folder is added in git.

**Comment by pihyper** [comment]
Well, deploying an empty commit to rebuild, using the commands

git commit --allow-empty -m "Rebuild, heroku"
git push heroku master

did the trick.

**Comment by adinutzyc21** [comment]
If anyone is looking for this answer, for me it was changing the name of the app folder that caused the error.

In Heroku Dashboard, Config Vars, make sure you have 
`METEOR_APP_DIR` set to the correct name.

**Comment by darkdoon** [comment]
For me, it was that my local master branch didn't contain the .meteor directory. If your current development is in another branch, (eg *mybranch*) do
```
git push heroku mybranch:master
```
