### ISSUE TITLE
Can't find meteor app error while deploying to Heroku. 

### ISSUE THREAD

**Issue by vandretti** [AdmitHub/meteor-buildpack-horse#116]
This is my first time trying to deploy my Meteor 1.3 app. Here's the error log: 

Buildpack set. Next release on ddmr will use https://github.com/AdmitHub/meteor-buildpack-horse.git.
Run git push heroku master to create a new release using this buildpack.
D:/filterbunny git push heroku masterCounting objects: 47, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (42/42), done.
Writing objects: 100% (47/47), 448.63 KiB | 0 bytes/s, done.
Total 47 (delta 12), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
remote: -----> Node.js app detected
remote: FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' supdirectory.  (Tried /tmp/build_812f5d670f794808cd7d216e00d07a0f)
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ddmr.
remote: 
To https://git.heroku.com/ddmr.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ddmr.git'

**Comment by yourcelf** [comment]
Is the `.meteor` directory checked in to git?  Is the meteor app (and the `.meteor` directory) in the root of your source repository, or in a subdirectory?

**Comment by vandretti** [comment]
That was the issue. By removing  .meteor/  in .gitignore file, the app was deployed to heroku successfully.  Thank you!
