### ISSUE TITLE
cannot deploy apps suddenly

### ISSUE THREAD

**Issue by y-ich** [AdmitHub/meteor-buildpack-horse#117]
Hi.

I was repeatedly deploying my app for debugging, and suddenly failed to deploy it around 00:00 July 1st UTC.
I checked its previous successful version and my other apps but all failed.
The error is,

    remote: Installation failed.
    remote: 
    remote:  !     Push rejected, failed to compile Node.js app

I am afraid that heroku changed some specification important for meteor-buildpack-horse.
Does anyone have same experience and know workarounds?

Thanks.

**Comment by vandretti** [comment]
I got the same problem a few minutes ago.

**Comment by vandretti** [comment]
I tried another [buildpack](https://github.com/petestreet/heroku-buildpack-meteor) that use node version v0.10.41, and it seemed to work.

**Comment by y-ich** [comment]
As I use meteor 1.3.2.4 for package compatibility issue, I needed node 0.10.43.
The latest version of heroku's node 0.10.x became 0.10.46 and it might be the cause.
