### ISSUE TITLE
Building with 1.4 beta

### ISSUE THREAD

**Issue by dpeet** [AdmitHub/meteor-buildpack-horse#120]
Is there a way to get this build pack to work with the 1.4 beta? I tried to simply upgrade and push to heroku and the build hung while downloading

**Comment by yourcelf** [comment]
@dpeet could you try the beta branch?  I suspect the problem is with the version of nodejs.  We've been pinning to node v0.10.x, but the meteor 1.4 beta upgrades to node v4.  Our beta branch is now always using the npm/node that are bundled with meteor rather than downloading a separate version:

    heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta

**Comment by dpeet** [comment]
@yourcelf thanks for the suggestion!  I gave it a go, but got another error which is posted below.  I upgraded to METEOR@1.4-beta.7

`Starting process with command `HOME=.meteor-dist ./meteor-dist/.meteor/meteor node .meteor/heroku_build/app/main.js || HOME=.meteor-dist .meteor-dist/meteor-node .meteor/heroku_build/app/main.js`

assert.js:93
throw new assert.AssertionError({
^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
bash: .meteor-dist/meteor-node: No such file or directory
Process exited with status 127
State changed from starting to crashed
State changed from crashed to starting`

**Comment by dpeet** [comment]
As a matter of note, I rolled back to METEOR@1.3.4.1, but used the beta buildpack, and it solved my issue which was 
`Error: ENOENT, no such file or directory '/node_modules/@slack/client/node_modules/winston/node_modules/pkginfo/lib'`

It looked somewhat similar to #114  but obviously hard to tell exactly.

**Comment by yourcelf** [comment]
This is the issue: meteor/meteor#7338

The meteor node and meteor npm commands are not using the release's versions. Perhaps this means that we can't (yet?) rely on these undocumented methods of obtaining the bundled node/npm.

(1.4-beta targets node v4, which is why you get the runtime error there -- a built-in that is not present in node v0.10 is being referenced.)

**Comment by ramijarrar** [comment]
v1.3.4.2 is out now and addresses this issue: running ```meteor npm``` and ```meteor node``` will respect the specified release.

**Comment by yourcelf** [comment]
Great!  It looks like the beta branch is building 1.4-beta releases successfully now.  Can you confirm this?

**Comment by maxnowack** [comment]
It works now after the v1.3.4.2 release :)

**Comment by dpeet** [comment]
I'm not testing with the beta anymore, but I can also confirm it works with 1.3.4.2

**Comment by maxnowack** [comment]
I have done my test with v1.4-rc.0

**Comment by jalavosus** [comment]
Confirming beta branch works with Meteor 1.4-rc.1

**Comment by juandanceswild** [comment]
Beta branch and Meteor 1.4-rc.1 deployed to Heroku correctly.

**Comment by lirbank** [comment]
Just confirming `https://github.com/AdmitHub/meteor-buildpack-horse.git#beta` works with the official Meteor 1.4 release.

**Comment by jamiter** [comment]
The 1.4 build is succeeding, but the slug size almost tripled. Issue: https://github.com/AdmitHub/meteor-buildpack-horse/issues/125

**Comment by dhamaniasad** [comment]
Can confirm that the beta branch works with v1.4. Not so much for master. I'm also not facing any slug size issues.

**Comment by jsantana90** [comment]
Just deployed with the beta branch of buildpack-horse in heroku with a meteor version 1.4 app

It went from `Done: 32.8M` to `Done: 213.6M`

**Comment by yourcelf** [comment]
Thanks everyone who's commented on beta working correctly.  I just pushed a new version to #beta which fixes the issues in #125, and also speeds up compilation (helping address #64), and retains backwards compatibility to older meteor's.  Please try it out; if I don't hear any negative reports in the next 24 hours I'll merge with master.

**Comment by dpeet** [comment]
Just gave it a go (Meteor 1.3.5.1). Size went from 250mb to 25 AND it was faster!  Awesome work @yourcelf!
