### ISSUE TITLE
deploying Rocket.Chat on Flynn is stuck

### ISSUE THREAD

**Issue by hadifarnoud** [AdmitHub/meteor-buildpack-horse#127]
I'm using [Flynn](flynn.io) (which is open source version of Heroku and compatible with heroku buildpacks).

I'm stuck at your buildpack trying to `sed` meteor path (I think). here is the log

``` log
hadifarnoud@MacBook-Pro chat (master)$ git push flynn master
Counting objects: 49358, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14540/14540), done.
Writing objects: 100% (49358/49358), 35.56 MiB | 190.00 KiB/s, done.
Total 49358 (delta 33749), reused 49210 (delta 33693)
-----> Building chat...
-----> Fetching custom buildpack
-----> Node.js app detected
-----> Listing HEROKU_ environment variables
       HEROKU_APP_ID:
       HEROKU_APP_NAME:
       HEROKU_DYNO_ID:
       HEROKU_RELEASE_VERSION:
       HEROKU_SLUG_COMMIT:
       HEROKU_SLUG_DESCRIPTION:
remote: + dirname -- /tmp/buildpacks/custom_heroku-buildpack-meteor/bin/compile
remote: + cd -P -- /tmp/buildpacks/custom_heroku-buildpack-meteor/bin
remote: + cd ..
remote: + pwd -P
remote: + BUILDPACK_DIR=/tmp/buildpacks/custom_heroku-buildpack-meteor
remote: + APP_CHECKOUT_DIR=/tmp/build
remote: + APP_SOURCE_DIR=/tmp/build
remote: + [ -n  ]
remote: + [ ! -d /tmp/build/.meteor ]
remote: + [ ! -d /tmp/build/.meteor ]
remote: + mktemp -d /tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-XXXX
remote: + METEOR_DIR=/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J
remote: + COMPILE_DIR_SUFFIX=.meteor/heroku_build
remote: + COMPILE_DIR=/tmp/build/.meteor/heroku_build
remote: + METEOR_PRETTY_OUTPUT=0
remote: + mkdir -p /tmp/build /tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J /tmp/build/.meteor/heroku_build
remote: + PATH=/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J/.meteor:/tmp/build/.meteor/heroku_build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
remote: + [ -z http://chat.kamva.ir ]
remote: + [ -z http://chat.kamva.ir ]
remote: + echo -----> Installing node
remote: + curl -sS --get https://semver.io/node/resolve/0.10.x
-----> Installing node
remote: + NODE_VERSION=0.10.46
remote: + NODE_URL=http://s3pository.heroku.com/node/v0.10.46/node-v0.10.46-linux-x64.tar.gz
remote: + curl -sS+ tar -zxf - -C /tmp/build/.meteor/heroku_build --strip 1
remote:  http://s3pository.heroku.com/node/v0.10.46/node-v0.10.46-linux-x64.tar.gz -o -
remote: + export npm_config_prefix=/tmp/build/.meteor/heroku_build
remote: + export CPATH=/tmp/build/.meteor/heroku_build/include
remote: + export CPPPATH=/tmp/build/.meteor/heroku_build/include
remote: + echo -----> Installing meteor
remote: + curl+ HOME=/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J /bin/sh
remote:  -sS https://install.meteor.com
-----> Installing meteor
remote: Downloading Meteor distribution
remote:
remote: Meteor 1.4 has been installed in your home directory (~/.meteor).
remote: Writing a launcher script to /usr/local/bin/meteor for your convenience.
remote: This may prompt for your password.
remote: sudo: no tty present and no askpass program specified
remote:
remote: Couldn't write the launcher script. Please either:
remote:
remote:   (1) Run the following as root:
remote:         cp "/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J/.meteor/packages/meteor-tool/1.4.0/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote:   (2) Add "$HOME/.meteor" to your path, or
remote:   (3) Rerun this command to try again.
remote:
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: + METEOR=/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J/.meteor/meteor
remote: + HOME=/tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J /tmp/buildpacks/custom_heroku-buildpack-meteor/meteor-Jp5J/.meteor/meteor --version
remote: + sed -e s/Meteor /METEOR@/
```

can you explain what are the steps your buildpack is doing? maybe I can fork this and make changes to be compatible with Flynn as well.

**Comment by yourcelf** [comment]
Take a look at `bin/compile` ; the source is very verbosely commented.  If there's something more specific you don't understand ask and I can clarify.

But additionally: please try the beta branch which will be merged in shortly -- `https://github.com/AdmitHub/meteor-buildpack-horse.git#beta`.  The parts around meteor version introspection have been rewritten there.

**Comment by yourcelf** [comment]
#130 (the beta branch) is now merged; so please try that and see how things go.

**Comment by hadifarnoud** [comment]
I'm still having issues @yourcelf 
https://gist.github.com/hadifarnoud/085cfe7c96c701fe0219ec27e62bed82

**Comment by yourcelf** [comment]
This looks like the [key line](https://gist.github.com/hadifarnoud/085cfe7c96c701fe0219ec27e62bed82#file-flynn-L119):
```
 WARNING: The output directory is under your source tree.
```
There are a few important directories for the buildpack's bundling process:
 - `BUILDPACK_DIR`: this is the directory the buildpack is checked out in.  In your gist, this appears to be `/tmp/buildpacks/custom_meteor-buildpack-horse/`.
 - `APP_CHECKOUT_DIR`: this is the directory the meteor application is checked out in. In your gist, this appears to be `/tmp/build/`.

The build script creates a temporary directory in `BUILDPACK_DIR` to act as the destination for building the bundle. In the gist you linked, this resolves to [`/tmp/buildpacks/custom_meteor-buildpack-horse/build-zy5r`](https://gist.github.com/hadifarnoud/085cfe7c96c701fe0219ec27e62bed82#file-flynn-L107).

It appears that this directory is being regarded as a child of `/tmp/build/` by meteor -- perhaps there's some symlinking going on?  At any rate, this results in meteor attempting to bundle up the result of its bundling, which recurses infinitely and fails.

I'd check with Flynn to see how it handles the directory structure for /tmp/buildpacks and /tmp/build.  If it's not possible to make sure those are not linked on top of each other, you'll need to modify the [line that sets `BUNDLE_DEST`](https://github.com/AdmitHub/meteor-buildpack-horse/blob/ae206a7ef1da461f7f8cf0c7a16b77affb5019e9/bin/compile#L193) to put it somewhere outside of `BUILDPACK_DIR`).

**Comment by hadifarnoud** [comment]
I was unable to fix this issue. I used docker image to deploy on Flynn. thankfully they support it.

**Comment by engelgabriel** [comment]
@hadifarnoud I have merged back upstream into our fork, check if it helped?

https://github.com/RocketChat/meteor-buildpack-horse/commit/e9c41de7ac52d6d528aeb4fc0ec64eba48ae1d77

**Comment by yourcelf** [comment]
It's been a while, so I'm going to close this issue. If folks are still impacted by it please reopen.
