### ISSUE TITLE
Ignore devDependencies in package.json

### ISSUE THREAD

**Issue by merlinpatt** [AdmitHub/meteor-buildpack-horse#128]
When I deploy, this buildpack installs all my packages, including those in `devDependencies`, like `chai`, and `stylelint`.

Can this be ignored? When I'm deploying to production, I don't need these packages. That's why I put them in `devDependencies`

**Comment by yourcelf** [comment]
Many people use devDependencies for packages that are required to compile their app, like webpack, babel, etc.  So we include dev dependencies for the installation that will build the final slug; but we do not include the dev dependencies in the final slug.  There are two stages to building: setting up an environment that can run `meteor build` (this includes dev dependencies), and then installing dependencies on the built app (this does not include dev dependencies).
