### ISSUE TITLE
For meteor 1.4, the Node version need to be 4.x

### ISSUE THREAD

**Issue by 2013gang** [AdmitHub/meteor-buildpack-horse#131]

**Comment by yourcelf** [comment]
See #102, #112, #125, and #120.  Will be fixed when we merge in #130 real soon now.  In the mean time, you can use `https://github.com/AdmitHub/meteor-buildpack-horse.git#beta`.

**Comment by yourcelf** [comment]
Fixed in #130.  Should work out-of-the-box with 1.4 now.

**Comment by 2013gang** [comment]
Cool! Thanks
