### ISSUE TITLE
[Error]: Push failed when deploying new changes to app

### ISSUE THREAD

**Issue by vinaypuppal** [AdmitHub/meteor-buildpack-horse#138]
App gets deployed first time successfully but if i try to deploy new changes i get following build error. Using `METEOR@1.4.0.1` in my app

``` bash
-----> Node.js app detected
-----> Meteor version: Meteor 1.4.1
-----> Checking if this meteor version supports --server-only
cp: cannot stat ‘/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node\n/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.1.126z7o8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node’: No such file or directory
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by vinaypuppal** [comment]
I updated my app to `METEOR@1.4.1` and checked, then the push to heroku is successful. Don't know why it failed with `METEOR@1.4.0.1` so i am leaving this issue open.

**Comment by m0ngr31** [comment]
I'm getting the same error. I'm on 1.3.* and it's failing. I was able to deploy yesterday, but now it's not working.

**Comment by eric-burel** [comment]
Hi, this issue still appears randomly with `METEOR@1.4.1`
#132 solution is more a workaround than a fix, as it makes the cache unusable and thus increase the build time (that's okay but a bit annoying when you use Heroku as a staging environment and push four times a day).

**Comment by bmustata** [comment]
Temporary fix: heroku config:set BUILDPACK_CLEAR_CACHE=1

**Comment by yourcelf** [comment]
Please try the beta release of meteor-buildpack-horse, which should fix problems with locating node/npm within the build:
```
heroku config:unset BUILDPACK_CLEAR_CACHE
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta
```

**Comment by kmullings** [comment]
I got a similar error...

`remote: -----> Node.js app detected
remote: -----> Meteor version: Meteor 1.4.1.1
remote: -----> Checking if this meteor version supports --server-only
remote: cp: cannot stat ‘/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node\n/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.1_1.a0j76k++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node’: No such file or directory
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed`

This is my fix...

I checked the Meteor version.

> meteor --version
Meteor 1.4.1.1

I then changed METEOR@1.4.0.1 in .meteor/release to METEOR@1.4.1.1

**Comment by yourcelf** [comment]
The beta branch has now been merged into master.  It should fix all of these existing problems with cache clearing and node/npm versions.  If you needed `BUILDPACK_CLEAR_CACHE=1` before, you could try unsetting that for slightly faster builds now.
