### ISSUE TITLE
Push Rejected. Failed to Compile Node.js app

### ISSUE THREAD

**Issue by allpratik** [AdmitHub/meteor-buildpack-horse#14]
Hi,

For the first time I'm trying to deploy a Meteor app to Heroku. I am also using MongoLab hosted db. I just started out with the LeaderBoard example, added the buildpack and tried to push the comitted code. Everything was fine until this following error occurred.

************************************************************************************************

-----> Bundling bundle
Installing Meteor 0.8.3:
 * 'meteor' build tool (version cef2bcd356)
 * Package updates: accounts-base accounts-facebook accounts-github
   accounts-google accounts-meetup accounts-meteor-developer accounts-oauth
   accounts-password accounts-twitter accounts-ui accounts-ui-unstyled
   accounts-weibo amplify appcache application-configuration
   audit-argument-checks autopublish autoupdate backbone binary-heap blaze
   blaze-tools bootstrap browser-policy browser-policy-common
   browser-policy-content browser-policy-framing callback-hook check
   code-prettify coffeescript coffeescript-test-helper ctl ctl-helper d3 deps
   dev-bundle-fetcher disable-oplog ejson email facebook facts follower-livedata
   force-ssl geojson-utils github google handlebars html-tools htmljs http
   id-map insecure jquery jquery-history jquery-layout jquery-waypoints
   js-analyze js-analyze-tests json jsparse less livedata localstorage logging
   meetup meteor meteor-developer meyerweb-reset minifiers minimongo
   mongo-livedata oauth oauth-encryption oauth1 oauth2 observe-sequence
   ordered-dict preserve-inputs random reactive-dict reload reload-safetybelt
   retry routepolicy service-configuration session sha showdown spacebars
   spacebars-compiler spacebars-tests spiderable srp standard-app-packages
   star-translate startup stylus templating test-helpers test-in-browser
   test-in-console tinytest twitter ui underscore underscore-tests webapp weibo

'remove-platform' is not a Meteor command. See 'meteor --help'.

 !     Push rejected, failed to compile Node.js app

To git@heroku.com:testleader.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:testleader.git'
D:\Meteor\backup [master +4 ~0 -0 !]>

**Comment by AndrewMagliozzi** [comment]
I think your problem is that you're on an old version of meteor.  You
should upgrade and try again.

On Wed, Jan 21, 2015 at 2:34 PM, Pratik Khandagale <notifications@github.com

**Comment by allpratik** [comment]
@AndrewMagliozzi Yes, you were right. I was using 0.8.3 version of Meteor on windows. Now shifted to Ubuntu and this error is vanished. But now some different error has emerged.

git push heroku master
Initializing repository, done.
error: src refspec master does not match any.
error: failed to push some refs to 'git@heroku.com:mytesttodos.git'


I had already added Mongolabs addon. Still it says failed to push some refs! :(

**Comment by yourcelf** [comment]
``src refspec master does not match any`` sounds like you haven't committed any files to your local git repository yet.

**Comment by yourcelf** [comment]
Hey @allpratik, it looks like this was more an issue with your git/meteor setup than an issue with the buildpack, so I'm closing it now.  Feel free to reopen if you think there's still a problem with the buildpack.
