### ISSUE TITLE
Push rejected

### ISSUE THREAD

**Issue by aexonicarindam** [AdmitHub/meteor-buildpack-horse#145]
Counting objects: 445, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (431/431), done.
Writing objects: 100% (445/445), 4.51 MiB | 61.00 KiB/s, done.
Total 445 (delta 132), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: -----> Installing meteor
remote: curl: (3) Illegal characters found in URL
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 1: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97remote: /.meteor/meteor: not found
remote: -----> Meteor version: 
remote: -----> Checking if this meteor version supports --server-only
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 1: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97remote: /.meteor/meteor: not found
remote: -----> Attempting to remove android platform.
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 127: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bberemote: /.meteor/meteor: not found
remote: -----> Moving on.
remote: FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to qup-release-7.
remote: 
To https://git.heroku.com/qup-release-7.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/qup-release-7.git'

**Comment by Nevtep** [comment]
Same happens for me

**Comment by yourcelf** [comment]
@nevtep: your issue is different, and is probably the same as #132.  Set `BUILDPACK_CLEAR_CACHE=1` and try building again:

    heroku config:set BUILDPACK_CLEAR_CACHE=1

@aexonicarindam: what are the contents of `.meteor/release` for your project?  I see the `Illegal characters found in URL` error from curl, which leads me to suspect something's funny there.

**Comment by ickyrr** [comment]
I had the same error, but I think mine was of a different reason.
I looked up heroku logs and saw the one causing the error was the mongo lab addon, which i'm not quite sure if it's related to the one you're experiencing. So I removed the mongolab addon. And then I tried doing `meteor update --all-packages` and everything worked fine. Or you can refer to [this](https://meteorcoder.wordpress.com/2016/09/24/how-to-deploy-meteor-apps-with-heroku/) post.

**Comment by yourcelf** [comment]
@aexonicarindam, @Nevtep: Please try the beta release of meteor-buildpack-horse, which should fix problems with locating node/npm within the build:
```
heroku config:unset BUILDPACK_CLEAR_CACHE
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta
```

**Comment by raza2022** [comment]
@yourcelf `heroku config:set BUILDPACK_CLEAR_CACHE=1` works for me

**Comment by yourcelf** [comment]
The beta branch has now been merged into master.  It should fix all of these existing problems with cache clearing and node/npm versions.  If you needed `BUILDPACK_CLEAR_CACHE=1` before, you could try unsetting that for slightly faster builds now.
