### ISSUE TITLE
Nginix

### ISSUE THREAD

**Issue by hydrotik** [AdmitHub/meteor-buildpack-horse#149]
I've found bits and pieces of info around integrating this with Nginix, is there a relatively standard process for this?

**Comment by yourcelf** [comment]
This buildpack is intended for deploying to heroku.  There are some people that have used it for other heroku-like environments such as [Dokku](https://github.com/dokku/dokku) or [Flynn](https://flynn.io/).  These deployment targets are all a different level of abstraction from Nginx -- they might use nginx internally, or they might not (Heroku doesn't); either way, this buildpack won't know or care about what frontend webserver is executing its slug.

If you're interested in deploying a meteor project on your own server using nginx, you might consider a [tutorial like this](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx).  If you want to use a PaaS provider like Heroku, this buildpack might be a place to look.
