### ISSUE TITLE
babel-runtime npm package could not be found in your node_modules  

### ISSUE THREAD

**Issue by llama** [AdmitHub/meteor-buildpack-horse#156]
``` Error: The babel-runtime npm package could not be found in your node_modules  
 directory. Please run the following command to install it: 
   meteor npm install --save babel-runtime 
     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9) 
     at fileEvaluate (packages/modules-runtime.js:181:9) 
     at require (packages/modules-runtime.js:106:16) 
     at packages/babel-runtime.js:139:15 
     at packages/babel-runtime.js:150:3 
     at /app/.meteor/heroku_build/app/programs/server/boot.js:295:34 
     at Array.forEach (native) 
     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11) 
     at /app/.meteor/heroku_build/app/programs/server/boot.js:128:5 
     at /app/.meteor/heroku_build/app/programs/server/boot.js:344:5 ```

**Comment by yourcelf** [comment]
Sorry you're having trouble, but this isn't enough info for us to work with -- please reopen an issue using the issue template.  The template's there for a reason; we really need that info to find the problem.

 - Is this a runtime problem, or a failure to build?
 - Can you explain what you're trying to do, and where it's failing?
 - What is the content of your `.meteor/release` file?
 - What is the buildpack version you're using?
 - Please include more of the logs.

**Comment by llama** [comment]
Related: https://github.com/meteor/meteor/issues/8032

**Comment by fernandoheb** [comment]
Actually now it is related to https://github.com/meteor/meteor/issues/8912.
I'm also facing the same. after upgrade to meteor 1.5
I followed the 8032 and manage to pass through the git push, but when I try to open the app I get stuck Im my home without load any element but the background and with the error:
 
![image](https://user-images.githubusercontent.com/10677459/28747131-3b180022-746e-11e7-9dbc-d25895d65c9f.png)

any idea?
