### ISSUE TITLE
H18 - Server Request Interrupted

### ISSUE THREAD

**Issue by sasneutrino** [AdmitHub/meteor-buildpack-horse#159]
Hello,

I've installed your buildpack on new fresh heroku dyno and made no modification to it, but I'm getting approx 8 error "H18 - Server Request Interrupted" per day. Since I've made no modification to the installation yet, this tells me that these errors are from the buildpack, did you notice similar errors for you?

All the best,
Chris

**Comment by yourcelf** [comment]
It's been a while and haven't heard any other confirmations or complaints of this issue -- so I'm going to assume it's an issue with application code. I'm going to close for now unless we can get some more info on a cause that points to meteor-buildpack-horse.
