### ISSUE TITLE
Force-SSL

### ISSUE THREAD

**Issue by KamuelaFranco** [AdmitHub/meteor-buildpack-horse#16]
How do we enable this package's functionality on Heroku?

**Comment by pauldowman** [comment]
Assuming you've added a cert to the Heroku app and SSL works (or else you're just using the Heroku app.com domain) then you shouldn't need to do anything other than add the package. It should just redirect to the same url but with HTTPS.

**Comment by corsonknowles** [comment]
Hi Paul, 
Heroku in many instances requires that you redirect www to @, but with the 'force ssl' package installed, it attempts to redirect https://example.com to https://www.example.com, which does not resolve. Any advice on handling this?

**Comment by pauldowman** [comment]
@corsonknowles I have not seen Heroku require that you redirect `www` to `@`, and in fact I think they recommend the opposite, that you should use `www` not the apex/root domain so that it can be a CNAME: https://devcenter.heroku.com/articles/apex-domains

**Comment by corsonknowles** [comment]
Thanks Paul! My apologies, I misspoke above. When following the standard setup instructions for Heroku and Google Domains, with both a forwarding instruction and a cname to redirect all users to www, using Force SSL will result in no page rendering at https://example.com. Meanwhile, entering via an unsecured connection at either www or root will work fine, as will going directly to the https://www version, which is where all the traffic is served.

Personally, our team has overcome this issue by adding Cloudflare as a CDN and having them rewrite incoming requests for us. Having only hosted a few apps on Heroku's somewhat particular but popular framework, I was hesitant to try a more brute force approach like adding an .htaccess file

I think now that I have described it properly, the redurect issue is one that could be reproduced and would remain an issue for other users. 

And this is conjecture, but it probably would not be limited to Google Domains, but extends to most users following Heroku's standard instructions. 

Anyways, thanks for all your work, our team has come across your contributions several times while building our new meteor app this week

**Comment by pauldowman** [comment]
The setup we use is:

*  `force-ssl` enabled
* `ROOT_URL` = `https://www.example.com`
* A redirect from `http://example.com' to `httpS://example.com' (done however your DNS provider likes to do this, we use Route 53 so it's using an S3 bucket)

With this setup it is not possible to go to an unsecured connection at either http://www.example.com, or http://example.com you will be redirected to the canonical URL with SSL (i.e. https://www.example.com). 

The only way you would likely go to http://example.com is when you just type `example.com` into your browser with no `http://` or `https://`.  This is common. But I think the chance of someone actually typing the full httpS://example.com (with the S) into their browser is basically 0 so I don't worry about the fact that nothing is served at that URL.
