### ISSUE TITLE
Require Issue Causing Crash

### ISSUE THREAD

**Issue by keplersj** [AdmitHub/meteor-buildpack-horse#166]
##### Type of problem
 - Runtime problem after the build succeeds

##### Contents of `.meteor/release`
```
METEOR@1.4.2.3
```

##### Buildpack version
```
=== blerp-production Buildpack URL
https://github.com/AdmitHub/meteor-buildpack-horse.git

```

##### Logs
```
Error: Cannot find module '../imports/components/page-bite'
     at Function.require.resolve (packages/modules-runtime.js:129:19)
     at Module.resolve (packages/modules-runtime.js:81:25)
     at Module.Mp.import (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:61:29)
     at meteorInstall.server.main.js (server/main.js:1:586)
     at fileEvaluate (packages/modules-runtime.js:181:9)
     at require (packages/modules-runtime.js:106:16)
     at /app/.meteor/heroku_build/app/programs/server/app/app.js:216:1
     at /app/.meteor/heroku_build/app/programs/server/boot.js:295:34
     at Array.forEach (native)
     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
 State changed from starting to crashed
 Process exited with status 1
```

##### Deployment target
Heroku

**Comment by yourcelf** [comment]
Is the missing module checked in to git?  If it's an npm package, is it included in package.json?  See https://guide.meteor.com/using-npm-packages.html#installing-npm

**Comment by keplersj** [comment]
It's there. I'm trying to deploy an application that we've been deploying to Galaxy, but we're seeing if Heroku will work better for us.

**Comment by keplersj** [comment]
After some debugging it looks like the bundle built on Heroku doesn't include files not in the `server` directory (`imports` in my case) in the final bundle.

When I ran `METEOR build $BUILD_OPTIONS --server $ROOT_URL $SERVER_ONLY_FLAG --directory $BUNDLE_DEST` locally the final `app.js` bundle had the required files from non-`server` directories.

**Comment by yourcelf** [comment]
The most likely cause of this is that the file not found on Heroku is not checked in to git, and so is not available for heroku to build.  Are you sure that the file is committed?  Might there be an over-broad rule in .gitignore that is excluding it?

There is nothing intrinsic to this buildpack or the build process that would exclude files not in the server directory.

**Comment by keplersj** [comment]
It's making it to heroku. When I `heroku run bash` in I can see the file and all the other files in `imports` under `/app`

Having looked through the `compile` script in the buildpack I don't see any reason why the app isn't building correctly. All of the necessary files are making it to heroku, the app just isn't bundling correctly on push.

I've done multiple pushes at this point, from both my development machine and GitLab CI, and get the same crashing build everytime.

**Comment by keplersj** [comment]
I moved all the code in `imports` to `common`. Deploys work now.
