### ISSUE TITLE
Getting an error while push heroku server

### ISSUE THREAD

**Issue by shemeermali** [AdmitHub/meteor-buildpack-horse#167]
##### Type of problem

 - Failure to build

##### Summary
Errors prevented bundling:
remote: While minifying app code:
remote: packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error: 
remote: 
remote: SyntaxError: Unexpected token name «i», expected punc «;» at
remote: node_modules/joi/lib/index.js line 185
remote: 
remote: within packages/modules.js (line: 43867, col: 17, pos: 5453877):
remote: 
remote: for (let i = 0; i < children.length; ++i) {
remote: 
remote: at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
remote: at packages/minifyStdJS_plugin.js:145:9
remote: at Array.forEach (native)
remote: at UglifyJSMinifier.processFilesForBundle
remote: (packages/minifyStdJS_plugin.js:130:9)
remote: 
remote: 
remote: While minifying app code:
remote: packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error: 
remote: 
remote: SyntaxError: Unexpected token name «i», expected punc «;» at
remote: node_modules/joi/lib/index.js line 185
remote: 
remote: within packages/modules.js (line: 43869, col: 17, pos: 5454129):
remote: 
remote: for (let i = 0; i < children.length; ++i) {
remote: 
remote: at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
remote: at packages/minifyStdJS_plugin.js:145:9
remote: at Array.forEach (native)
remote: at UglifyJSMinifier.processFilesForBundle
remote: (packages/minifyStdJS_plugin.js:130:9)
remote: 
remote: 
remote:  !     Push rejected, failed to compile Node.js app.

##### Contents of `.meteor/release`
METEOR@1.4.3.2

```

```

##### Buildpack version
Getting an error while push heroku server
```

```

##### Logs

```

```

**Comment by RobAWilkinson** [comment]
I had this same issue my fix was removing the default minify js and instead adding `abernix:standard-minifier-js@1.2.2`

**Comment by yourcelf** [comment]
Looks like a few folks have found this to be a minifier issue, so I'll close this for now. Please reopen if you're still impacted adn evidence points to it being a buildpack issue.
