### ISSUE TITLE
Packages downgrading during deploy

### ISSUE THREAD

**Issue by imajus** [AdmitHub/meteor-buildpack-horse#17]
I've noticed that more and more packages are downgrading during deploy to Heroku. It was't a problem before but now when I've started using undescrore string package it's just stopped working on Heroku servers.
How can I prevent downgrading at all?
```
-----> Bundling bundle
ios: platform is not in this project
android: platform is not in this project
crawler: updating npm dependencies -- crawler...

Changes to your project's package version selections:

aldeed:collection2                   downgraded from 2.3.2 to 2.3.1
aldeed:template-extension            downgraded from 3.4.0 to 3.1.1
ian:accounts-ui-bootstrap-3          downgraded from 1.2.27 to 1.2.20
particle4dev:cheerio                 downgraded from 1.1.0 to 1.0.0
reywood:iron-router-ga               downgraded from 0.5.3 to 0.4.1
underscorestring:underscore.string*  downgraded from 3.0.3 to 2.4.0


* These packages have been updated to new versions that are not backwards
```

**Comment by krstffr** [comment]
Yeah, I also have this issue.

@imajus: you can prevent it by setting an explicit version when adding your packages, like `meteor add reywood:iron-router-ga@1.1.0`, but then I don't think your packages will update when you run `meteor update`, so it's kind of annoying. It should solve the deployment problem though!

The same issue is described here: https://github.com/djhi/heroku-buildpack-meteorite/issues/3

**Comment by engelgabriel** [comment]
I think that was a bug in Meteor, that is fixed now. Should this issue be closed?

**Comment by AndrewMagliozzi** [comment]
Thanks for the heads up!
