### ISSUE TITLE
Question: How to scale using this buildpack?

### ISSUE THREAD

**Issue by thebarty** [AdmitHub/meteor-buildpack-horse#170]
Hi guys,

I am hoping that someone using this package can give some info on what to do and how successful it works for them.

For me this works great using 1 dyno, BUT **what if my userbase grows and I want to bring in a 2d and 3rd dyno? What would I have to do???**

Do I need to setup a load-balancer myself? How much work would I have to put into that?

Thanks a lot for your tips!

**Comment by smothers** [comment]
Heroku automatically load balances dynos. You probably want to switch from the default random balancing to [Session Affinity ](https://devcenter.heroku.com/articles/session-affinity) so DDP connections get the same dyno every time.

**Comment by yourcelf** [comment]
Thanks @smothers for the pointers on load balancing and session affinity. I'm going to close this for now; please re-open if there are more specific concerns that the buildpack needs to address.
