### ISSUE TITLE
first deployment sticks

### ISSUE THREAD

**Issue by hounaine** [AdmitHub/meteor-buildpack-horse#171]
App works perfectly, I use METEOR_SETTINGS, BUILDPACK_PRELAUNCH_METEOR, BUILDPACK_URL, ROOT_URL, but the code and all files are the one i deployed first time, each deployment it never changes.

 - is there any bundle folder to delete ?
 - or buildhorse can set a variable to clear cache ?

 "METEOR@1.4.4.2"
BUILD TO HEROKU
last buildpack version

**Comment by yourcelf** [comment]
Make sure you're committing any new changes to git.  Please see [Heroku's git documentation](https://devcenter.heroku.com/articles/git) for more details -- without a new git commit in the master branch of your local repository, heroku will continue to use the old code.
