### ISSUE TITLE
Meteor 1.5 failing : out of memory

### ISSUE THREAD

**Issue by fadomire** [AdmitHub/meteor-buildpack-horse#173]
##### Type of problem

 - Failure to build

##### Summary

since i updated to meteor 1.5 the build is failing with error:
```
remote:     1: /* anonymous */(aka /* anonymous */) [/app/tmp/cache/meteor/.meteor/packages/standard-minifier-js/.2.1.0.nt2b9c++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-traverse/lib/path/family.js:152] [pc=0x202f31fced93] (this=0xbb9114041b9 <undefined>,_=0x8b4d70efe29 <a Node with map 0x23bec7f38769>,i=0)
remote:     2: arguments adaptor frame: ...
remote:
remote: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: line 107:   502 Aborted                 HOME="$METEOR_DIR" "$METEOR_DIR/.meteor/meteor" $ARGS
```

i tried with ```METEOR@1.5``` and ```METEOR@1.4.2```

i tried with ```BUILDPACK_CLEAR_CACHE```

i tried also to ```heroku repo:gc -a appname``` and ``` heroku repo:purge_cache -a appname```

##### Contents of `.meteor/release`

```
METEOR@1.4.4.2

```

##### Buildpack version

```
https://github.com/AdmitHub/meteor-buildpack-horse.git
```

##### Deployment target

deploying to heroku

**Comment by fadomire** [comment]
related to https://github.com/meteor/meteor/issues/8157#issuecomment-307528600

not buildpack

**Comment by aboobakkar** [comment]
worked me for settings use heroku config var 
TOOL_NODE_FLAGS = "--max-old-space-size=4096"

**Comment by madguy02** [comment]
@aboobakkar  where did you add heroku config var?
