### ISSUE TITLE
No access to meteor shell and other command line tools?

### ISSUE THREAD

**Issue by bloudermilk** [AdmitHub/meteor-buildpack-horse#175]
##### Type of problem

 - Runtime problem after the build succeeds

##### Summary

Expected: I expect to have access to the `$ meteor` command line tool in order to access, for example, the Meteor shell. 

Observed: When I use `$ heroku run bash` and poke around my build, I cannot find the `meteor` executable. I have even checked `.meteor/heroku_build`.

##### Contents of `.meteor/release`

```
METEOR@1.4.4.2
```

##### Buildpack version

```
https://github.com/AdmitHub/meteor-buildpack-horse.git
```

##### Deployment target

Heroku

**Comment by hexsprite** [comment]
@bloudermilk this is typical of a Meteor deploy, the `meteor` command is only part of the development environment. That said, I heard that there is an unofficial way to get `meteor shell` working in a production environment.

**Comment by bloudermilk** [comment]
@hexsprite this totally makes sense. Coming from a Rails background I hadn't considered that there wouldn't be a production console. Thank you for taking the time to explain!
