### ISSUE TITLE
Update for Meteor 1.5 and Node 4.8.4+

### ISSUE THREAD

**Issue by alanwunsche** [AdmitHub/meteor-buildpack-horse#178]
##### Type of problem

 - The Node.js team has announced that a high severity remote Denial of Service (DoS) Constant Hashtable Seeds vulnerability in Node.js versions 4.x through 8.x has been patched in the following versions:

##### Summary

Need to make sure the build works with Node 4.8.4 and above.

##### Contents of `.meteor/release`

```
METEOR@1.5 looks to have Node 4.8.3 
```

##### Buildpack version

```
.
```

##### Logs

```
.
```

##### Deployment target

.

**Comment by yourcelf** [comment]
Upgrade to Meteor 1.5.1.  See meteor's issue: https://github.com/meteor/meteor/issues/8903

meteor-buildpack-horse uses the version of node that ships with meteor, so if you upgrade to 1.5.1, you will get node 4.8.4.
