### ISSUE TITLE
core.js needs to be added when deploying with Meteor 1.6

### ISSUE THREAD

**Issue by hems** [AdmitHub/meteor-buildpack-horse#184]
- Runtime problem after the build succeeds

##### Summary

Using meteor version 1.6, deploying to heroku the first time i accessed the website my chrome console asked me to `meteor npm install core-js`

##### Contents of `.meteor/release`
```
METEOR@1.6
```

##### Buildpack version
```
https://github.com/AdmitHub/meteor-buildpack-horse.git
```

##### Deployment target
heroku

**Comment by tosbourn** [comment]
@hems were you deploying a brand new application and using 1.6, or did you upgrade your application that was already deploying fine to 1.6 when it broke?

**Comment by hems** [comment]
it was a new app i believe, anyway after installing core-js everything worked great. it's just weird that it only "complained" when running on my staging environment

**Comment by myt588** [comment]
same problem here
meteor@1.6
once core.js is installed
everything seems to be working fine

**Comment by hems** [comment]
I can confirm this actually happened on an Ubuntu box I ran a new 1.6 meteor project, without using this build pack ( just manually installed it there ) 

So it seems it's actually related to running 1.6 on Linux and not about building it with this build pack!

**Comment by persac** [comment]
For completeness, my experience:

1. Local (OSX) update from 1.5.4 to 1.6: no problems
2. Deploy to Heroku using buildpack-horse: blank page, Chrome console asks me to install `npm core-js`
3. Locally run `meteor npm install --save core-js`
4. Deploy again: app now runs fine on Heroku

**Comment by hems** [comment]
@persac exactly, this happens even if you run the application on a linux server yourself, without using heroku or the buildpack so i reckon it's not related to this repository!

**Comment by assadvirgo** [comment]
On both Ubuntu and OSX facing the similar issue installed core-js bable-runtime but nothing helped.
