### ISSUE TITLE
Instrument the app with tools such as new relic?

### ISSUE THREAD

**Issue by hems** [AdmitHub/meteor-buildpack-horse#192]
##### Type of problem
Need to instrument the app using new relic, is it possible to run "require('newrelic')" before anything else?

##### Summary
I believe because horse buildpack "de-meteriorize" the application the instrumentation on my server isn't happening as early as new relic would like to.

<img width="953" alt="screen shot 2018-02-27 at 19 46 02" src="https://user-images.githubusercontent.com/27327/36727406-1129ff5e-1bf8-11e8-8970-7d0da4a6610c.png">

##### Deployment target
Heroku

**Comment by hems** [comment]
@nilesh-parab thanks for the suggestions!

perhaps galaxy comes with kadira out of the box too right?

**Comment by nilesh-parab** [comment]
@hems seems they already have done it [Galaxy Kadira](https://blog.meteor.com/introducing-galaxy-professional-built-in-apm-5e063839a4aa)

**Comment by hems** [comment]
thanks 🙏
