### ISSUE TITLE
Question: How do we set HTTP Headers?

### ISSUE THREAD

**Issue by micchickenburger** [AdmitHub/meteor-buildpack-horse#201]
How do we set HTTP headers?  The Heroku Static Buildpack allows for HTTP headers in static.json.  See here for more information: [Using HTTP Headers to Secure Your Site](https://blog.heroku.com/using-http-headers-to-secure-your-site)

How can we set HTTP headers with this buildpack?  Thank you!

**Comment by yourcelf** [comment]
Headers are the responsibility of the Meteor application; there's nothing intrinsic to this buildpack for setting headers.

See https://stackoverflow.com/questions/15959501/how-to-add-cors-headers-to-a-meteor-app as an example for adding headers to a response with Meteor.

**Comment by micchickenburger** [comment]
Thank you :)
