### ISSUE TITLE
Oplog support ?

### ISSUE THREAD

**Issue by po-jo** [AdmitHub/meteor-buildpack-horse#207]
##### Type of problem
 - Runtime problem after the build succeeds

##### Summary
Hello there,

Build and deployment are fine, but I see _Not Using Oplog_ on the subscriptions in MontyAPM (monitoring tool based on Kadira), even if I use a paid Mlab plan with replica set.  Is there something special to use oplog ?

Thanks :)

##### Contents of `.meteor/release`
METEOR@1.6.0.1

##### Buildpack version
https://github.com/AdmitHub/meteor-buildpack-horse.git

##### Deployment target
Heroku

**Comment by maxnowack** [comment]
Have you configured the `MONGO_OPLOG_URL` environment variable? (https://docs.meteor.com/environment-variables.html#MONGO-OPLOG-URL)

**Comment by po-jo** [comment]
hi @maxnowack thanks for the help 👍
Silly me, there was no  MONGO_OPLOG_URL. Maybe this variable could be in the buildpack documentation since it can lead to performance issues ?
