### ISSUE TITLE
meteor authentication not working for heroku deploy

### ISSUE THREAD

**Issue by jasonshark** [AdmitHub/meteor-buildpack-horse#29]
I've deployed my iron-cli meteor app to heroku using this buildpack. The app shows up ([here](https://js-meteor-todos.herokuapp.com/)) but I cannot log in using meteor developer accounts.

I get the error " Something went wrong: that application does not exist."
![screen shot 2015-05-29 at 2 02 38 pm](https://cloud.githubusercontent.com/assets/3578908/7892702/74e8ec68-060b-11e5-9268-1aed7aaafca0.png)

I added redirect urls:

![screen shot 2015-05-29 at 2 03 45 pm](https://cloud.githubusercontent.com/assets/3578908/7892715/988a10f2-060b-11e5-885f-d146d17ee072.png)

And I also created a file `config/production/env.sh` where I have:

```
export ACCOUNTS_METEOR_ID='<my-app-id>'
export ACCOUNTS_METEOR_SECRET='<my-secret-key>'
```

In app/server/bootstrap.js I specify:

```
ServiceConfiguration.configurations.upsert(
  { service: 'meteor-developer' },
  {
    $set: {
      clientId: process.env['ACCOUNTS_METEOR_ID'],
      secret: process.env['ACCOUNTS_METEOR_SECRET'],
      loginStyle: 'popup'
    }
  }
);
```

This all follows the setup from the [eventedmind screencast](https://www.eventedmind.com/classes/build-a-multi-page-app-with-iron-meteor-6737880d). How can I get authentication working in production with heroku?

**Comment by AndrewMagliozzi** [comment]
I'm not sure this is an issue with the buildpack.  It seems more like an
issue with Meteor Auth.  Perhaps someone else can shed light here or on
Stackoverflow.

**Comment by yourcelf** [comment]
I'm closing this now -- please re-open if this seems to be an ongoing problem with the buildpack.
