### ISSUE TITLE
Hangs during "Downloading Meteor distribution"

### ISSUE THREAD

**Issue by benmgreene** [AdmitHub/meteor-buildpack-horse#32]
I've been using this buildpack for months without problem. But today, when trying to `git push heroku master`, I can't get past around ~16% during the "Downloading Meteor distribution" step:

```
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.20 KiB | 0 bytes/s, done.
Total 9 (delta 7), reused 0 (delta 0)
remote: Git submodules detected, installing:
remote: Submodule path 'packages/accounts-entry': checked out 'bc13810c0ee60b7608621a28ad203553e70c2ae1'
remote: Submodule path 'packages/chosen-package': checked out '1a3336a08702c02329f43d3950112d8d5f04b25c'
remote: Submodule path 'packages/meteor-chartjs': checked out 'f34fc5859964bb6d6627cee5b994613b34eb019d'
remote: Submodule path 'packages/meteor-typeahead': checked out '155cf1c3f08600c63b9947aaeb1a93c404b1d6a3'
remote: Submodule path 'packages/relative-time': checked out '3ebad072c0cead8fe5e6328ef88c2cc318ce9dd2'
remote: 
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Node.js app detected
remote: -----> Installing node
remote: -----> Installing meteor
remote: Downloading Meteor distribution
remote: ###########                                                               15.8%
```

The only thing I can think of is that I haven't upgraded my heroku instance from Cedar-10 to Cedar-14. Thoughts?  Help is greatly appreciated.

**Comment by yourcelf** [comment]
That's the output of curl within the script.  So if it's hanging, my guess is some network problem between heroku and meteor.com.  Can you try it again if and see if it works?

I haven't seen any issues yet with cedar-10, cedar-14, or projects migrated from 10 to 14, so my guess is that this isn't the problem.

**Comment by yourcelf** [comment]
Closing this.. please re-open if the problem persists and seems to be a problem with the buildpack (and not with Heroku's network).
