### ISSUE TITLE
Cannot find ionic scss

### ISSUE THREAD

**Issue by weijian19391** [AdmitHub/meteor-buildpack-horse#33]
Hi! 

I've tried the setting stack to -14 solution (but i believe that the latest version of heroku doesn't require that setting already since they have deprecated the previous stack version https://devcenter.heroku.com/articles/cedar), and i'm still getting the error of 
````
remote: Errors prevented bundling:
remote: While building the application:
remote: /tmp/build_c76b59a4fbbd167b917775f6cee37410/client/stylesheets/app.scss:4:9:
remote: Scss compiler error: file to import not found or unreadable:
remote: .meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic
remote: Current dir: /tmp/build_c76b59a4fbbd167b917775f6cee37410/client/stylesheets/
remote: 
remote: 
remote: 
remote:  !     Push rejected, failed to compile Node.js app

````

any help will be greatly appreciated!

**Comment by yourcelf** [comment]
Cedar-10 vs cedar-14 shouldn't be (and hasn't yet been) an issue, as far as I know.

Your issue looks like it's related to #19 -- meteor needs to launch once to build your static scss files before it can build the bundle.  Try setting ``BUILDPACK_PRELAUNCH_METEOR = 1`` in your heroku environment and rerunning.

**Comment by weijian19391** [comment]
Hi @yourcelf !

Thanks for your prompt reply! i've followed your suggestion, and have managed to deploy to heroku, however, now the deployment doesn't show any CSS at all! Here's the link to my deployment: http://mighty-forest-6021.herokuapp.com/

Any idea what may have caused this??
