### ISSUE TITLE
Latest commit broke my build

### ISSUE THREAD

**Issue by skirunman** [AdmitHub/meteor-buildpack-horse#36]
Getting this error on build after this commit https://github.com/AdmitHub/meteor-buildpack-horse/commit/bad37c499fb2747fb4045a42299deca2d10c149d

I'm using Meteoric and have set BUILDPACK_PRELAUNCH_METEOR to 1 to get around this issue https://github.com/meteor/meteor/issues/2796 as noted at https://github.com/meteoric/ionic-sass but looks like this is no longer working as a workaround.

-----> Building Meteor with ROOT_URL: https://myapp.herokuapp.com/
The iOS platform is not installed; skipping build for it.
Errors prevented bundling:
While building the application:
/tmp/build_63d6acf628976f4a375615fc39cfad54/app/client/stylesheets/main.scss:149:9:
Scss compiler error: file to import not found or unreadable:
.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic
Current dir:
/tmp/build_63d6acf628976f4a375615fc39cfad54/app/client/stylesheets/
 !     Push rejected, failed to compile Node.js app

**Comment by yourcelf** [comment]
If you're starting from a clean checkout, and you launch meteor with the ``--server`` flag, do you get this error?

Are you using iOS or other build targets in your code?

**Comment by skirunman** [comment]
Thanks for the help. Yes, using IOS as build target as well as ios-device. I did a meteor reset and built for ios-device with --server flag pointing to my heroku app. 

The issue is the heroku build is failing when I try to do a git push heroku master. I had deployed on heroku just fine many times before using this buildpack.

**Comment by yourcelf** [comment]
Please try setting your buildpack to https://github.com/AdmitHub/meteor-buildpack-horse.git#devel and see if that branch builds correctly for you.  See https://github.com/AdmitHub/meteor-buildpack-horse/commit/648e2ed3a435c87f111e83a858a4f9f25e207357 for an explanation of what I think is going on.

**Comment by yourcelf** [comment]
If anyone else is using ``BUILDPACK_PRELAUNCH_METEOR`` in conjunction with iOS build targets, please try using the devel branch (set buildpack URL to  https://github.com/AdmitHub/meteor-buildpack-horse.git#devel ).  I want to get feedback on this change before merging.

**Comment by skirunman** [comment]
Thanks and sorry for the delay testing this. Looks like the latest release works for me. Thanks again for the quick fix!

**Comment by yourcelf** [comment]
Great, glad to hear.
