### ISSUE TITLE
Using to connect to PostgreSQL database

### ISSUE THREAD

**Issue by tnedich** [AdmitHub/meteor-buildpack-horse#38]
Can this buildpack be used to connect to PostgreSQL (with use of numtel/pg package)

**Comment by yourcelf** [comment]
Maybe.  I haven't used numtel/pg before, but please try.

If you're not using mongolab, you'll want to fork this buildpack and remove references to them from the release file: https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/release

If you have other addons that are needed for postgresql you'll need to enable those.  If you need other extra things to be installed on the server (beyond standard meteor packages) you may need to write an "extras" script to pull those in.
