### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by thdoan** [AdmitHub/meteor-buildpack-horse#41]
Instruction step 2 has a typo: `heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git`

It should be `buildpack:set`.

**Comment by yourcelf** [comment]
Hmmm... the docs indicate buildpacks:set is correct: https://devcenter.heroku.com/articles/buildpacks#using-a-custom-buildpack .  The command line client, too, shows "buildpacks" as the name of the command (try ``heroku help` and ``heroku help buildpacks``).

The docs do *also* say "You can specify an exact version of a buildpack by using a git revision with the buildpack:set command" -- I wonder if that's a typo.  Heroku seems to support a "list of buildpacks" now, I'm not sure if that has something to do with it; I've only ever used one.

**Comment by thdoan** [comment]
I'm not sure what changed, but I got an error when I used `buildpacks:set` saying there's no such command; the error went away when I changed it to `buildpack:set`. Strange.

**Comment by KamuelaFranco** [comment]
I thought this may have been my issue, but I really believe `buildpacks:set` is the correct command, and this should be closed.
