### ISSUE TITLE
Push rejected, failed to compile Node.js app

### ISSUE THREAD

**Issue by jmwenda** [AdmitHub/meteor-buildpack-horse#42]
I keep getting this error. I already have committed to my local repo and the log is as follows. Seems the temporary file created states "mv can not stat", resulting in the error. 

https://gist.github.com/jmwenda/2a9f6d9686a2a1080d40

What could be the problem?

**Comment by tr90814** [comment]
I had what looks like the same issue, I set my `ROOT_URL`, pushed again and that seemed to fix it.

**Comment by AndrewMagliozzi** [comment]
Thanks for the issue, Jude.  Did Tom's suggesting fix it?

**Comment by simonv3** [comment]
I got this same issue, you can see the project here: http://github.com/simonv3/quick-survey/, and the app.json file here: https://github.com/simonv3/quick-survey/blob/develop/app.json

I feel like ROOT_URL should maybe default to the app-name?

**Comment by simonv3** [comment]
I got it working in the end - had to include the `.meteor` folder (kind of logical in hindsight) as well as giving a full URL in ROOT_URL. However, the URL I supplied got overwritten and just the name of the app was used, so I'm not sure if that made a difference in the end.

**Comment by simonv3** [comment]
Scratch all of that. I'm getting this error again, specifically: 

```
mv: cannot stat ‘/tmp/buildpack_f7be3f1647892740a1495a86332e69e4/build-Fk7n/bundle’: No such file or directory
```

**Comment by yourcelf** [comment]
Can you share the repository you're trying to build?  That would help a lot with trying to debug.

Also, you can fork this buildpack and [uncomment the "verbose" flag, ``set -x``](https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L8) to enable verbose printing of everything the buildpack is doing.

**Comment by simonv3** [comment]
It's still the same one from before http://github.com/simonv3/quick-survey/

I'm doing some debugging here: https://github.com/simonv3/meteor-buildpack-horse/

Looks like what's happening is that the `meteor build --directory` command isn't creating the bundle directory (works fine locally). I've added a tar command (which is not pretty, but can probably suppressed, have to look at the options) and changed rmdir to rm -rf. Building now and see how far it gets.

**Comment by simonv3** [comment]
Update: Looks like the changes I made make it all the way through deployment. I wasn't adding a ROOT_URL because of testing, and that actually only fails when the application launches. 

```
2015-09-02T17:01:45.036040+00:00 app[web.1]:     at Object.Meteor.absoluteUrl (packages/meteor/url_common.js:21:1)
2015-09-02T17:01:45.036032+00:00 app[web.1]: Error: Must pass options.rootUrl or set ROOT_URL in the server environment
2015-09-02T17:01:45.036042+00:00 app[web.1]:     at bcrypt (packages/accounts-password/email_templates.js:7:1)
2015-09-02T17:01:45.036045+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-password.js:85:4
2015-09-02T17:01:45.036047+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-password.js:895:3
2015-09-02T17:01:45.036049+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:222:10
2015-09-02T17:01:45.036051+00:00 app[web.1]:     at Array.forEach (native)
2015-09-02T17:01:45.036054+00:00 app[web.1]:     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
2015-09-02T17:01:45.036056+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:117:5
2015-09-02T17:01:44.968470+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:245
```

So that feels like it would be a false lead on that anyway. I'm wondering if it's possible to remove that requirement entirely and just set it to the app-name + herokuapp.com?

**Comment by yourcelf** [comment]
Not everyone uses app-name + herokuapp.com as their public facing URL.  We could try to check if ROOT_URL is empty first, and set it if only if it's empty..

**Comment by simonv3** [comment]
That's what I meant, sorry. I'm currently trying to figure out how to get a hold of the app name in the env variables.

**Comment by simonv3** [comment]
And another update: so when I supply the root_url this time around, the untarring didn't work anymore. So `meteor build --server $ROOT_URL --directory $BUNDLE_DEST` creates the `bundle/` directory properly but if no ROOT_URL is passed it just creates the .tar? This is strange because I definitely had added a ROOT_URL when I started :/.

**Comment by maartenbusstra** [comment]
I'm having this issue with the Meteor 1.2-rc.11

**Comment by yourcelf** [comment]
@maartenbusstra: do you have ROOT_URL set?

**Comment by maartenbusstra** [comment]
@yourcelf Definitely!
Here's the log:
https://gist.github.com/maartenbusstra/31c6206604a14b1c3a55

**Comment by yourcelf** [comment]
@maartenbusstra that log indicates that heroku is using Meteor 1.1.0.3, not Meteor 1.2.

This buildpack currently installs with the latest stable Meteor.  But if you have 1.2-specific code and try to bundle it with 1.1.0.3, it'll almost certainly fail.  So in short: yours is a different issue -- you'll need to fork this buildpack and change [the installation of Meteor](https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L65-L67) to install the release candidate rather than stable.

**Comment by maartenbusstra** [comment]
@yourcelf Thanks for the help. I had it work with a different project that's running on 1.2. That's kind of weird.

Do you happen to know where I can "curl" the RC?

**Comment by yourcelf** [comment]
Nope, don't know where. You could add a line to ``meteor update --release METEOR@1.2-rc.11`` after the curl'ed installation finishes.

**Comment by maartenbusstra** [comment]
The output from Heroku was kind of odd, but it's working.
For anyone that's having the same issue, it's here:
https://github.com/mdrnize/meteor-buildpack-horse

Use at your own risk, though!

**Comment by followyoureyes** [comment]
Hej guys, I kind of have the same problem. See the error message here: https://gist.github.com/followyoureyes/56a58e97e6631b58a1a5. I did all the steps from this blog post: http://justmeteor.com/blog/deploy-to-production-on-heroku/. I had the Meteor app running on my_app.meteor.com and on an own url my_app.org. Could this be the problem that there are some conflicts with setting ROOT_URL ?

(I don't want to make too many changes in my app since I'm hoping that Meteor Galaxy will soon be a better fit then heroku - just wanted to give heroku a try since it's to some extend free).

**Comment by followyoureyes** [comment]
And these are the packages I'm using:
accounts-password        1.1.4  Password support for accounts
accounts-ui              1.1.6  Simple templates to add login widgets to an app
blaze-html-templates     1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                    1.1.0  Check whether a value matches a pattern
edgee:slingshot          0.7.1  Directly post files to cloud storage services, such as AWS-S3.
ejson                    1.0.7  Extended and Extensible JSON library
email                    1.0.8  Send email messages
houston:admin            2.0.3* A zero-config Meteor Admin
iron:router              1.0.7* Routing specifically designed for Meteor
jquery                   1.11.4  Manipulate the DOM using CSS selectors
keiths:octicons          1.2.2  Octicons library for Meteor.js
logging                  1.0.8  Logging facility.
manuel:reactivearray     1.0.5  Reactive Array for Meteor
meteor-base              1.0.1  Packages that every Meteor app needs
meteorhacks:kadira       2.26.3  Performance Monitoring for Meteor
mobile-experience        1.0.1  Packages for a great mobile user experience
mongo                    1.1.3  Adaptor for using MongoDB and Minimongo over DDP
mrt:aws-sdk              0.2.0  Meteor smart package for AWS SDK node.js package
mystor:device-detection  0.2.0  Client-Side Device Type Detection & Template Switching with Optional Meteor-Router Support
random                   1.0.5  Random number generator and utilities
reload                   1.1.4  Reload the page while preserving application state.
session                  1.1.1  Session variable
spacebars                1.0.7  Handlebars-like template language for Meteor
spiderable               1.0.9  Makes the application crawlable to web spiders
standard-minifiers       1.0.2  Standard minifiers used with Meteor apps by default.
tracker                  1.0.9  Dependency tracker to allow reactive callbacks

**Comment by yourcelf** [comment]
The buildpack now reads from `.meteor/release` and upgrades meteor to the appropriate version if needed.

**Comment by jortegamo** [comment]
Hi, I have a problem with .meteor/release. I think I should try to upgrade meteor for my app. My current version is 1.2.0.2. while deploying console shows this error: cat: /tmp/build_f4132d93575831d3633ff3116884aebf/.meteor/release: No such file or directory

Some idea? Thanks

**Comment by JeanLebrument** [comment]
+1

**Comment by yourcelf** [comment]
@JeanLebrument or @jortegamo: do you have your meteor app in a subdirectory of your repository?  This buildpack currently expects to find `.meteor/` either in the root of the repository or in `app/.meteor/`.  See https://github.com/AdmitHub/meteor-buildpack-horse/issues/81 for more troubleshooting on that.

**Comment by JeanLebrument** [comment]
@yourcelf I just edited my post, mine isn't that similar

**Comment by yourcelf** [comment]
@JeanLebrument please open your issue as a new issue.  Please also include more of the output log -- I'd like to be able to see what happened before that line.
