### ISSUE TITLE
Installing TypeScript

### ISSUE THREAD

**Issue by dominikmayer** [AdmitHub/meteor-buildpack-horse#44]
I'm trying to get the [TypeScript compiler](https://github.com/meteor-typescript/meteor-typescript-compiler) running on Heroku. So far I'm lost because I don't know how to install typescript as a dependency.

At first I put `typescript` as a `devDependency` in a `package.json`. I tried to put that in the root as well as the `server` directory.

Now I [forked](https://github.com/dominikmayer/meteor-buildpack-horse) the repository and hardcoded `npm install -g typescript` which also doesn't work:

```
[…]
remote: Compiling TypeScript web.browser files...
remote: Errors prevented bundling:
remote: While building the application:
remote: 
remote: /tmp/build_ac7fb7c1f5d49d44191a629501dbcaf5/lib/typescript/custom_defs/collections.ts:1:1:
remote: error TS6053: File
remote: '/tmp/build_ac7fb7c1f5d49d44191a629501dbcaf5/lib/typescript/package_defs/all-definitions.d.ts'
remote: not found.
[…]
```

What is the proper way to add TypeScript (or any other npm module)?

**Comment by yourcelf** [comment]
NPM modules should install correctly if you list them in ``packages.json``, as is standard with [meteor npm](https://github.com/meteorhacks/npm).

I'm not sure about what specifically meteor-typescript-compiler requires -- you might try opening an issue there.  It looks to me from the error message you quote here that there is some file path issue with the compile script.  One place you might look is trying to install without the ``-g`` flag; I'm not sure what a "global" installation would mean in the context of a heroku dyno.

**Comment by dominikmayer** [comment]
Thanks for your reply. I hadn't know about _meteor npm._ Going to look into it. My original problem went away when I included the library and switched to demeteorizer.
