### ISSUE TITLE
meteor restart on heorku

### ISSUE THREAD

**Issue by stevenbarragan** [AdmitHub/meteor-buildpack-horse#46]
Does somebody knows how can I do ``meteor restart`` on heroku?

someting like 

```zsh
heroku run meteor restart
```

**Comment by yourcelf** [comment]
Running ``meteor restart`` doesn't make sense for a meteor app that has been "built".  The output of ``meteor build``, which is what is running on heroku, is a more or less plain nodejs app that doesn't make use of the "meteor tool" that you use in development.

You can restart the dyno with ``heroku restart``, but running commands as "meteor" won't help.

**Comment by stevenbarragan** [comment]
I see, thanks @yourcelf.

I'm trying to add this file into my scss
```scss
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons';
```

local works fine, but heroku can't complete the build, it says the file doesn't exist. I was thinking it's related to this https://github.com/meteor/meteor/issues/2606 or https://github.com/meteor/meteor/issues/2796, they suggest to do a ``meteor restart`` which on heroku as you say it doesn't make sense.

any idea?

I could close this issue an open another one since it seems it's not related at all.

**Comment by yourcelf** [comment]
See #19.  Set ``BUILDPACK_PRELAUNCH_METEOR=1`` in your environment to pre-launch meteor and build assets prior to bundling.

**Comment by stevenbarragan** [comment]
it works!

Thanks a lot.
