### ISSUE TITLE
Facebook auth with custom domains not working

### ISSUE THREAD

**Issue by lnmunhoz** [AdmitHub/meteor-buildpack-horse#49]
I'm having a problem on trying to authenticate with facebook with different domains. It works just with the domain specified in `ROOT_URL` variable. That means, my user only can use facebook login in domain with www (if the `ROOT_URL` is `http://www.mydomain.com` ) or without the www (if the `ROOT_URL` is `http://mydomain.com`)

I'm getting the following error message:
```
SecurityError: Blocked a frame with origin "http://www.mydomain.com.br" from accessing a frame with origin "http://mydomain.com.br". Protocols, domains, and ports must match.
```

All the possible callback urls are specified in advanced settings on facebook. This is an error maybe on meteor facebook package but I'm looking for some help here too.

**Comment by yourcelf** [comment]
I'm pretty sure this issue has nothing to do with ``meteor-buildpack-horse``.  The error looks like a something that's happening between facebook's iframe and your browser's URL, which is an application issue that has nothing to do with building and publishing on heroku.

One workaround you could try is ensuring that the user is always at the correct domain -- see http://www.meteorpedia.com/read/HTTP_Redirects for some pointers on how to do redirects using ``WebApp.connectHandlers``.  Check if the hostname associated with the request is the same as the value of ROOT_URL, and issue a redirect if not.
