### ISSUE TITLE
unknown package: isobuild:compiler-plugin

### ISSUE THREAD

**Issue by sagarjauhari** [AdmitHub/meteor-buildpack-horse#52]
getting the error `unknown package: isobuild:compiler-plugin` on heroku

**Comment by yourcelf** [comment]
Do you still have this issue?  If so, can you give more info about your setup -- ideally, source code for a meteor app that exhibits this issue?

**Comment by yourcelf** [comment]
I'm going to close this for now -- please reopen if you think there's an ongoing problem with the buildpack.
