### ISSUE TITLE
Disable spinner/loading bar in console

### ISSUE THREAD

**Issue by maartenbusstra** [AdmitHub/meteor-buildpack-horse#54]
This can sometimes be annoying in build/ci logs.

Apparently it's possible with an env variable:
https://github.com/meteor/meteor/issues/5208

**Comment by yourcelf** [comment]
Thanks. I've fixed this in https://github.com/AdmitHub/meteor-buildpack-horse/commit/24a6392a901855daae9cca51718d4dc6e40a35f0 ; however, unfortunately meteor still prints a progress bar and percentage indicator even with `METEOR_PRETTY_OUTPUT=0` while downloading itself. So there should be less log noise now, but not none.
