### ISSUE TITLE
Meteor fails to start after build

### ISSUE THREAD

**Issue by branco91** [AdmitHub/meteor-buildpack-horse#55]
Hi folks, 

I am having some issues launching my meteor app after the build.

Locally works fine and I am able to push successfully as well (with the build completing as per normal).

But once I attempt to open the link of the application in my server, I get a 404 as if the application was offline.

I decided to manually launch it within the Docker container and this is the error I see:

his project is already at Meteor 1.2.1, the latest release.
                                              
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EXDEV, rename '/app/.meteor/local/isopacks/npm-container'

Has anyone faced this before?

**Comment by yourcelf** [comment]
I'm closing this old issue here.  If you're still having trouble, please re-open the issue and provide some more details -- ideally, source code to a meteor app that causes the problem.

**Comment by gg2001** [comment]
Yes, I am getting the same problem when I try to push the example Todos app. I am following the instructions [here](http://stackoverflow.com/questions/26867881/application-error-after-deploying-meteor-1-0-app-on-heroku). However, I am not using a mongoLabgs URL, but instead a the free mongoLabs 500mb addon. The app runs fine on a local server, and when I push it to heroku, there are no errors, but I get the Application Error when I open the app. Why is this? Here is my log:

> egaumbp:todos gg$ git push heroku master
> Counting objects: 3, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (3/3), done.
> Writing objects: 100% (3/3), 319 bytes | 0 bytes/s, done.
> Total 3 (delta 2), reused 0 (delta 0)
> remote: Git submodules detected, installing:
> remote: 
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
> remote: -----> Node.js app detected
> remote: -----> Installing node
> remote: -----> Installing meteor
> remote: Downloading Meteor distribution
> remote: ######################################################################## 100.0%
> remote: 
> remote: Meteor 1.3.1 has been installed in your home directory (~/.meteor).
> remote: 
> remote: Now you need to do one of the following:
> remote: 
> remote:   (1) Add "$HOME/.meteor" to your path, or
> remote:   (2) Run this command as root:
> remote:         cp "/tmp/buildpack20160416-160-cqvcpn/meteor-2qqX/.meteor/packages/meteor-tool/1.3.1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
> remote: 
> remote: Then to get started, take a look at 'meteor --help' or see the docs at
> remote: docs.meteor.com.
> remote: -----> Bundling bundle
> remote: npm WARN package.json ggtodos@0.0.1 No repository field.
> remote: npm WARN package.json ggtodos@0.0.1 No README data
> remote: npm WARN package.json ggtodos@0.0.1 No license field.
> remote: npm WARN engine postcss@5.0.19: wanted: {"node":">=0.12"} (current: {"node":"0.10.44","npm":"2.15.0"})
> remote: eslint-config-airbnb@6.2.0 node_modules/eslint-config-airbnb
> remote: 
> remote: eslint-plugin-react@4.3.0 node_modules/eslint-plugin-react
> remote: 
> remote: eslint@2.8.0 node_modules/eslint
> remote: ├── path-is-absolute@1.0.0
> remote: ├── imurmurhash@0.1.4
> remote: ├── path-is-inside@1.0.1
> remote: ├── pluralize@1.2.1
> remote: ├── strip-json-comments@1.0.4
> remote: ├── ignore@3.1.1
> remote: ├── progress@1.1.8
> remote: ├── estraverse@4.2.0
> remote: ├── globals@9.4.0
> remote: ├── text-table@0.2.0
> remote: ├── esutils@2.0.2
> remote: ├── user-home@2.0.0 (os-homedir@1.0.1)
> remote: ├── is-resolvable@1.0.0 (tryit@1.0.2)
> remote: ├── debug@2.2.0 (ms@0.7.1)
> remote: ├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
> remote: ├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
> remote: ├── require-uncached@1.0.2 (resolve-from@1.0.1, caller-path@0.1.0)
> remote: ├── mkdirp@0.5.1 (minimist@0.0.8)
> remote: ├── doctrine@1.2.1 (isarray@1.0.0, esutils@1.1.6)
> remote: ├── optionator@0.8.1 (fast-levenshtein@1.1.3, type-check@0.3.2, deep-is@0.1.3, levn@0.3.0, wordwrap@1.0.0, prelude-ls@1.1.2)
> remote: ├── glob@7.0.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
> remote: ├── shelljs@0.6.0
> remote: ├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
> remote: ├── is-my-json-valid@2.13.1 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
> remote: ├── inquirer@0.12.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, figures@1.5.0, ansi-escapes@1.3.0, through@2.3.8, cli-width@2.1.0, run-async@0.1.0, readline2@1.0.1, string-width@1.0.1, cli-cursor@1.0.2, rx-lite@3.1.2)
> remote: ├── file-entry-cache@1.2.4 (object-assign@4.0.1, flat-cache@1.0.10)
> remote: ├── js-yaml@3.6.0 (esprima@2.7.2, argparse@1.0.7)
> remote: ├── espree@3.1.3 (acorn@3.0.4, acorn-jsx@2.0.1)
> remote: ├── table@3.7.8 (slice-ansi@0.0.4, strip-ansi@3.0.1, tv4@1.2.7, string-width@1.0.1, xregexp@3.1.0, bluebird@3.3.5)
> remote: ├── es6-map@0.1.3 (d@0.1.1, es6-symbol@3.0.2, event-emitter@0.3.4, es6-iterator@2.0.0, es6-set@0.1.4, es5-ext@0.10.11)
> remote: ├── escope@3.6.0 (esrecurse@4.1.0, es6-weak-map@2.0.1)
> remote: └── lodash@4.11.1
> remote: 
> remote: eslint-plugin-meteor@3.4.0 node_modules/eslint-plugin-meteor
> remote: ├── lodash.memoize@4.0.1 (lodash._mapcache@4.1.5)
> remote: ├── path-exists@2.1.0 (pinkie-promise@2.0.1)
> remote: ├── invariant@2.2.1 (loose-envify@1.1.0)
> remote: ├── lodash.find@4.2.0 (lodash._basefindindex@3.6.0, lodash._basefind@3.0.0, lodash._baseeach@4.1.2, lodash._baseiteratee@4.6.1)
> remote: ├── escope@3.6.0 (estraverse@4.2.0, esrecurse@4.1.0, es6-weak-map@2.0.1, es6-map@0.1.3)
> remote: ├── babel-register@6.7.2 (path-exists@1.0.0, home-or-tmp@1.0.0, mkdirp@0.5.1, source-map-support@0.2.10, babel-core@6.7.6, lodash@3.10.1, babel-runtime@5.8.38, core-js@2.2.2)
> remote: ├── babel-polyfill@6.7.2 (babel-regenerator-runtime@6.5.0, babel-runtime@5.8.38, core-js@2.2.2)
> remote: └── babel-runtime@6.6.1 (core-js@2.2.2)
> remote: 
> remote: autoprefixer@6.3.4 node_modules/autoprefixer
> remote: ├── normalize-range@0.1.2
> remote: ├── num2fraction@1.2.2
> remote: ├── postcss-value-parser@3.3.0
> remote: ├── browserslist@1.3.0
> remote: ├── postcss@5.0.19 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.3)
> remote: └── caniuse-db@1.0.30000436
> remote: 
> remote: faker@3.1.0 node_modules/faker
> remote: android: removed platform
> remote: -----> Building Meteor with ROOT_URL: http://ggtodos.herokuapp.com
> remote: Currently, it is only possible to build iOS apps on an OS X system.
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No description
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
> remote: 
> remote: > fibers@1.0.8 install /tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers
> remote: > node build.js || nodejs build.js
> remote: 
> remote: make: Entering directory `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/build'
> remote:   CXX(target) Release/obj.target/fibers/src/fibers.o
> remote:   CXX(target) Release/obj.target/fibers/src/coroutine.o
> remote:   CC(target) Release/obj.target/fibers/src/libcoro/coro.o
> remote:   SOLINK_MODULE(target) Release/obj.target/fibers.node
> remote:   COPY Release/fibers.node
> remote: make: Leaving directory `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/build'
> remote: Installed in `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
> remote: ansi-regex@0.2.1 node_modules/ansi-regex
> remote: 
> remote: ansi-styles@1.1.0 node_modules/ansi-styles
> remote: 
> remote: escape-string-regexp@1.0.5 node_modules/escape-string-regexp
> remote: 
> remote: has-ansi@0.1.0 node_modules/has-ansi
> remote: 
> remote: strip-ansi@0.3.0 node_modules/strip-ansi
> remote: 
> remote: supports-color@0.2.0 node_modules/supports-color
> remote: 
> remote: chalk@0.5.1 node_modules/chalk
> remote: 
> remote: eachline@2.3.3 node_modules/eachline
> remote: 
> remote: type-of@2.0.1 node_modules/type-of
> remote: 
> remote: amdefine@1.0.0 node_modules/amdefine
> remote: 
> remote: asap@2.0.3 node_modules/asap
> remote: 
> remote: underscore@1.5.2 node_modules/underscore
> remote: 
> remote: meteor-promise@0.5.1 node_modules/meteor-promise
> remote: 
> remote: promise@7.0.4 node_modules/promise
> remote: 
> remote: source-map-support@0.3.2 node_modules/source-map-support
> remote: 
> remote: semver@4.1.0 node_modules/semver
> remote: 
> remote: source-map@0.1.32 node_modules/source-map
> remote: 
> remote: fibers@1.0.8 node_modules/fibers
> remote: -----> Adding PATH environment
> remote: -----> Running extras
> remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
> remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
> remote: -----> Installing phantomjs.
> remote: 
> remote: -----> Discovering process types
> remote:        Procfile declares types     -> (none)
> remote:        Default types for buildpack -> web
> remote: 
> remote: -----> Compressing...
> remote:        Done: 97.2M
> remote: -----> Launching...
> remote:        Released v12
> remote:        https://ggtodos.herokuapp.com/ deployed to Heroku
> remote: 
> remote: Verifying deploy... done.
> To https://git.heroku.com/ggtodos.git
>    87427cb..e8558d3  master -> master
