### ISSUE TITLE
Does this buildpack require enabling session affinity?

### ISSUE THREAD

**Issue by wesleyfsmith** [AdmitHub/meteor-buildpack-horse#56]
I know with other build packs you have to enable heroku's session affinity.... was wondering if that was the case for this buildpack as well.

**Comment by pauldowman** [comment]
Yes, you need that for any Meteor app. (Unless you only have one Dyno of course... :smile:)

**Comment by wesleyfsmith** [comment]
Okay, if I've switch to long polling do you happen to know if session affinity is still needed?

**Comment by pauldowman** [comment]
Yes, it still is. Just do `heroku labs:enable http-session-affinity`. I wouldn't recommend disabling websockets, it will fall back to long polling anyway.
