### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by littlebang** [AdmitHub/meteor-buildpack-horse#6]
When i use this buildpack deploy to a remote server,its successfuly as expected,But when the remote server  reboot the app can not startup automatic .
I use dokku on the server side
:sos:

**Comment by yourcelf** [comment]
@littlebang, did you find resolution to this?

**Comment by mckinleymedia** [comment]
I got mine working, with the help of another guy.
I had a heck of a time, but it's working now.  The problem I had was with the syntax setting the build repository.  Instruction #2 says to do this:
heroku config:set BUILDPACK_URL=https://github.com/AdmitHub/meteor-buildpack-horse.git
We got it to work by doing this:
heroku buildpack:set https://github.com/AdmitHub/meteor-buildpack-horse.git -a <YOUR APPNAME>

Hope this helps someone.

**Comment by yourcelf** [comment]
Looks like this is a recent change in the buildpack API: https://devcenter.heroku.com/articles/buildpacks#using-a-custom-buildpack

I'll update the docs shortly.  Thanks @mckinleymedia !

**Comment by mckinleymedia** [comment]
Excellent!  Thanks @yourcelf !

**Comment by yourcelf** [comment]
Closing this now -- reopen if there are ongoing problems.

**Comment by juniobranco** [comment]
@yourcelf  I am actually having the same issues, the build and deployment is successful but a given app it will not start automatically (no errors in dokku logs app). I have also tried to use the meteor ToDo app and it works fine.

How should I trace the error? Where would the logs be inside the container of the app?

**Comment by yourcelf** [comment]
@juniobranco I have no experience using dokku or docker; I've only used this buildpack with heroku.
