### ISSUE TITLE
"This version of npm lacks support for important features" when pushing to heroku

### ISSUE THREAD

**Issue by 123ndy** [AdmitHub/meteor-buildpack-horse#60]
When I am pushing my code to heroku (```git push heroku master```), I get this WARN:
```
remote: -----> Bundling bundle
remote: -----> Building Meteor with ROOT_URL: https://batmobile.herokuapp.com
remote: npm WARN deprecated This version of npm lacks support for important features,
remote: npm WARN deprecated such as scoped packages, offered by the primary npm
remote: npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
remote: npm WARN deprecated latest stable version. To upgrade to npm@2, run:
remote: npm WARN deprecated 
remote: npm WARN deprecated   npm -g install npm@latest-2
remote: npm WARN deprecated 
remote: npm WARN deprecated To upgrade to the latest stable version, run:
remote: npm WARN deprecated 
remote: npm WARN deprecated   npm -g install npm@latest
remote: npm WARN deprecated 
remote: npm WARN deprecated (Depending on how Node.js was installed on your system, you
remote: npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
remote: npm WARN deprecated on Windows, run them from an Administrator prompt.)
remote: npm WARN deprecated 
remote: npm WARN deprecated If you're running the version of npm bundled with
remote: npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
remote: npm WARN deprecated will be bundled with a version of npm@2, which has some small
remote: npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
remote: npm WARN deprecated semver behavior.
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No description
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No README data
```
I am using: 
Meteor 1.2.1
NPM 2.14.14
Node 5.2.0

How can I solve this?

(I am relatively new to both Node and Meteor, so please let me know; and I will provide you with more information if needed :) )

**Comment by wesleyfsmith** [comment]
Having the exact same issue, would love to get some input on this.

**Comment by yourcelf** [comment]
This is a result of the buildpack running with node v0.10 (regardless of the node settings in your project).  I'm testing less ancient versions of node currently.  The warning can be safely ignored.

**Comment by yourcelf** [comment]
Just an update: it looks like Meteor does not support any node version higher than v0.10 yet.  Follow https://github.com/meteor/meteor/issues/5124 for more on that.  When meteor supports newer node, we'll upgrade and the npm warnings will go away.

**Comment by retani** [comment]
According to https://github.com/meteor/meteor/issues/5124, meteor now supports node 4! Will you update?

**Comment by yourcelf** [comment]
@retani Meteor Buildpack Horse now always uses the version of node that ships with the version of meteor your app targets.  So you get node v4+ if you're targeting a recent enough version of meteor with your app. We upgrade when you do. :)

**Comment by retani** [comment]
Oh, I understand now. Thanks!
