### ISSUE TITLE
Push Rejected

### ISSUE THREAD

**Issue by aexonicarindam** [AdmitHub/meteor-buildpack-horse#62]
remote: sh: 0: Can't open /tmp/build_ea59c436880c95874118ec9130918be3/packages/rocketchat-livechat/plugin/build.sh
remote: 
remote: /tmp/buildpack20160113-159-1l8sp7j/meteor-xkbL/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
remote: 						throw(ex);
remote: 						      ^
remote: Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
remote:     at Builder.write (/tools/isobuild/builder.js:225:13)
remote:     at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:353:10)
remote:     at /tools/isobuild/isopack.js:1346:27
remote:     at Array.forEach (native)
remote:     at Function._.each._.forEach (/tmp/buildpack20160113-159-1l8sp7j/meteor-xkbL/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote:     at _.each._.each.builder.generateFilename.directory (/tools/isobuild/isopack.js:1320:11)
remote:     at Array.forEach (native)
remote:     at Function._.each._.forEach (/tmp/buildpack20160113-159-1l8sp7j/meteor-xkbL/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote:     at /tools/isobuild/isopack.js:1233:9
remote:     at [object Object]._.extend.saveToPath (/tools/isobuild/isopack.js:1585:26)
remote:     at /tools/isobuild/isopack-cache.js:289:23
remote:     at /tools/utils/buildmessage.js:356:18
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:349:34
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:347:23
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)
remote:     at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopack-cache.js:227:18)
remote:     at /tools/isobuild/isopack-cache.js:166:14
remote:     at /tools/utils/buildmessage.js:356:18
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:349:34
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:347:23
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)
remote:     at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:158:20)
remote:     at /tools/isobuild/isopack-cache.js:73:14
remote:     at /tools/packaging/package-map.js:57:7
remote:     at Function._.each._.forEach (/tmp/buildpack20160113-159-1l8sp7j/meteor-xkbL/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
remote:     at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
remote:     at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopack-cache.js:72:24)
remote:     at /tools/project-context.js:735:25
remote:     at /tools/utils/buildmessage.js:356:18
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:349:34
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:347:23
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)
remote:     at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:734:18)
remote:     at /tools/project-context.js:257:35
remote:     at /tools/utils/buildmessage.js:356:18
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:349:34
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:347:23
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)
remote:     at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
remote:     at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
remote:     at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
remote:     at /tools/cli/commands.js:838:20
remote:     at /tools/utils/buildmessage.js:268:13
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:261:29
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:259:18
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at /tools/utils/buildmessage.js:250:23
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
remote:     at Object.capture (/tools/utils/buildmessage.js:249:19)
remote:     at Object.main.captureAndExit (/tools/cli/main.js:270:29)
remote:     at buildCommand (/tools/cli/commands.js:837:8)
remote:     at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
remote:     at /tools/cli/main.js:1378:23
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to penguin-khandelwal.
remote: 
To https://git.heroku.com/penguin-khandelwal.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/penguin-khandelwal.git'

**Comment by udisun** [comment]
+1

**Comment by JonathanHindi** [comment]
@aexonicarindam did you found a solution for this?

**Comment by yourcelf** [comment]
If you're still experiencing this issue, please provide more info on your setup or a link to source code of a meteor app that causes it.

**Comment by KHam0425** [comment]
Same issue here. I can't get beyond this:

` 
remote: Errors prevented isopacket load:[K
remote: 
remote: While loading isopacket `constraint-solver`:[K
remote: packages/meteor/server_environment.js:13:1: METEOR_SETTINGS are not valid JSON:[K
remote: settings.json[K
remote: at packages/meteor/server_environment.js:13:1[K

remote: at <runJavaScript-2>:50:4[K
remote: at <runJavaScript-2>:1274:3[K
remote: 
remote: 
remote: 
remote: /tmp/buildpack20160323-158-weak3h/meteor-b0wR/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245[K
remote: 						throw(ex);[K
remote: 						      ^[K

remote: Error: isopacket load failed?[K
remote:     at loadIsopacketFromDisk (/tools/tool-env/isopackets.js:280:11)[K
remote:     at /tools/tool-env/isopackets.js:87:23[K
remote:     at Object.exports.noYieldsAllowed (/tools/utils/fiber-helpers.js:65:14)[K
remote:     at Object.load (/tools/tool-env/isopackets.js:79:23)[K
remote:     at ProjectContext._.extend._buildResolver (/tools/project-context.js:681:22)[K
remote:     at /tools/project-context.js:467:29[K
remote:     at /tools/utils/buildmessage.js:356:18[K

remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:349:34[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:347:23[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)[K
remote:     at /tools/project-context.js:466:20[K
remote:     at /tools/packaging/catalog/catalog.js:100:5[K
remote:     at /tools/utils/buildmessage.js:268:13[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:261:29[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:259:18[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:250:23[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at Object.capture (/tools/utils/buildmessage.js:249:19)[K
remote:     at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)[K
remote:     at ProjectContext._.extend._resolveConstraints (/tools/project-context.js:465:13)[K
remote:     at /tools/project-context.js:257:35[K
remote:     at /tools/utils/buildmessage.js:356:18[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:349:34[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:347:23[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at Object.enterJob (/tools/utils/buildmessage.js:321:26)[K
remote:     at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)[K
remote:     at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)[K
remote:     at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)[K
remote:     at /tools/cli/commands.js:838:20[K
remote:     at /tools/utils/buildmessage.js:268:13[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:261:29[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:259:18[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at /tools/utils/buildmessage.js:250:23[K
remote:     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)[K
remote:     at Object.capture (/tools/utils/buildmessage.js:249:19)[K
remote:     at Object.main.captureAndExit (/tools/cli/main.js:270:29)[K
remote:     at buildCommand (/tools/cli/commands.js:837:8)[K
remote:     at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)[K
remote:     at /tools/cli/main.js:1378:23[K
remote: 
remote:  !     Push rejected, failed to compile Node.js app[K
remote: 
remote: Verifying deploy...[K
remote: 
remote: !	Push rejected to app.[K
remote: `

Deploying on heroku through git push, followed https://github.com/AdmitHub/meteor-buildpack-horse

**Comment by yourcelf** [comment]
@KHam0425, your issue looks different from @aexonicarindam's.  Your error complains that `METEOR_SETTINGS` is not valid JSON.  Are you sure the value you have set to `METEOR_SETTINGS` is valid JSON?

**Comment by AndrewMagliozzi** [comment]
Sometimes Heroku settings can be fickle when it comes to whitespace and new lines in environment settings.  Just an FYI based on my experience.

**Comment by yourcelf** [comment]
I'm going to close this for now -- please reopen if you think there's an ongoing problem with the buildpack.
