### ISSUE TITLE
Push rejected: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by kartikTT** [AdmitHub/meteor-buildpack-horse#63]
I am getting the following error when pushing to Heroku. Looks like it's a problem installing meteor? 

remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
remote: -----> Node.js app detected
remote: -----> Installing node
remote: -----> Installing meteor
remote: /bin/sh: 2: Syntax error: newline unexpected
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to grocery-beta.

**Comment by crsssl** [comment]
+1 Getting the same error

**Comment by yourcelf** [comment]
https://install.meteor.com is down.  #cloudfail

**Comment by RobertLowe** [comment]
Looks like `install.meteor.com` is serving raw HTML as the app appears to be crashed,

Discussion at: 
https://forums.meteor.com/t/https-install-meteor-com-is-down/16358

**Comment by ivycheung** [comment]
Thanks for the update. Ran into the same error myself.

**Comment by yourcelf** [comment]
It's back up now.
