### ISSUE TITLE
Support for 1.3 (modules)

### ISSUE THREAD

**Issue by maartenbusstra** [AdmitHub/meteor-buildpack-horse#66]
Because Meteor 1.3 includes NPM support, `npm install` might be required on the project repo. Are you planning on implementing support for that?

One possible issue might be that the project itself is using a newer NPM than included with the Nodejs version required by Meteor.

**Comment by yourcelf** [comment]
Does https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L96-L99 not do it?  If not, how does that need changing?

**Comment by maartenbusstra** [comment]
That's installing the dependencies of the bundled Node server. That's a different `package.json` file.

**Comment by maartenbusstra** [comment]
I'm looking into the build process now, by the way. I think it just needs a call to `npm install` before doing a build.

**Comment by maartenbusstra** [comment]
Yep, that does the trick.

Without first installing the packages from the project, the modules don't get installed:
`Uncaught Error: Cannot find module 'react'`

The Meteor build works fine when first installing the dependencies.

The question is, though, if Meteor will automatically do this for you in future versions of the build tool. I'm not sure if that would give any issues in regards to NPM versions being used. I did have to downgrade my NPM/Node versions to be able to use fibers after all.

Thoughts?

**Comment by maartenbusstra** [comment]
This fixes it for me:
https://github.com/mdrnize/meteor-buildpack-horse/commit/e63d7aa3acd3ad516893809b7062b200b4f0fc17

**Comment by c0cky** [comment]
@maartenbusstra thanks for the fix mate, worked well for me.

**Comment by maartenbusstra** [comment]
@c0cky Welcome. :)

**Comment by yourcelf** [comment]
Thanks all, fixed in https://github.com/AdmitHub/meteor-buildpack-horse/commit/33ab214e9af9c6d2eba07b8ef26e3f6f8e2b8ee0 .

**Comment by maartenbusstra** [comment]
Nice! :)
