### ISSUE TITLE
Deploy in Debug version

### ISSUE THREAD

**Issue by merlinpatt** [AdmitHub/meteor-buildpack-horse#69]
Meteor allows you to deploy with a `--debug` flag, which prevents minification and keeps certain packages (those with the `debugOnly` flag, [see the docs here](http://docs.meteor.com/#/full/packagedescription)) in the deployment.

Is there any way to do this with the buildpack?

It would be useful for staging environments.

**Comment by idanwe** [comment]
@merlinpatt any success with that?

**Comment by yourcelf** [comment]
You should be able to do this by adding a `--debug` flag to the [invocation of `meteor build`](https://github.com/AdmitHub/meteor-buildpack-horse/blob/33ab214e9af9c6d2eba07b8ef26e3f6f8e2b8ee0/bin/compile#L102-L103):

    echo "-----> Building Meteor with ROOT_URL: $ROOT_URL"
    HOME=$METEOR_DIR $METEOR build --server $ROOT_URL --directory $BUNDLE_DEST --debug

I think I'd prefer not to bake this into this buildpack or clutter with options for this at the moment; though if more folks have interest chime in or +1 here and we can add an env var or something.  For now, just fork the buildpack and add the flag as needed for your builds.

**Comment by idanwe** [comment]
@yourcelf Thanks, this is what I did
