### ISSUE TITLE
Question: Still Alive?

### ISSUE THREAD

**Issue by boustanihani** [AdmitHub/meteor-buildpack-horse#71]
Is the repo still alive?

Are there any alternatives ?

**Comment by benmgreene** [comment]
It’s definitely still “in use.”

**Comment by boustanihani** [comment]
http://justmeteor.com/blog/deploy-to-production-on-heroku/

**Comment by yourcelf** [comment]
We had a slowdown in dev time to service the buildpack, but I'm back on it now.  Thanks for the prod.
