### ISSUE TITLE
Install Local Packages on Heroku

### ISSUE THREAD

**Issue by swapnil7434** [AdmitHub/meteor-buildpack-horse#73]
Hello,

I want to install Local Packages or package from github on Heroku server. 
But i am keep getting following error.

remote: While selecting package versions:
remote: error: unknown package in top-level dependencies: jumpbyte:appout

So please let me know the steps for installing Local Packages or package from github on Heroku server

**Comment by yourcelf** [comment]
I don't think I understand -- could you provide a pointer to source code for a meteor app that exhibits the problem?  When you say "Local Packages", do you mean packages defined in `.meteor/packages`?

**Comment by swapnil7434** [comment]
Yes, i want to install jumpbyte:appout which is mentioned in .meteor/packages. which is not published on atomosphere. we have uploaded it on github. so how can i include it and install on heroku app.

**Comment by yourcelf** [comment]
If you can get your package into the `packages/` directory within the meteor app, it will work.  Two ways you might do this:

1. Clone `jumpbyte:appout` package into the packages directory.  Remove the `.git` folder.  This has the downside that it is no longer separate for version control.

2. Add `jumpbyte:appout` as a [git submodule](https://www.git-scm.com/book/en/v2/Git-Tools-Submodules) in the packages/ directory.  This has the advantage of keeping it on separate version control, but has the downside that git submodules take a fair bit of learning to use and can be a bit clunky.  Heroku correctly instantiates submodules when it clones your app.

I don't know of any other ways to get meteor to load a package, apart from putting it in `packages` or loading it from atmosphere.  How do you make it visible to meteor locally?

**Comment by yourcelf** [comment]
I'm going to close this for now -- please open a new issue if you think there's a problem with the buildpack.

**Comment by mrlowe** [comment]
Something that might be useful as a note on this case: heroku only supports submodules on a push, and not on an auto-deployed pull (or via other uses of its API). So you'll have to do a ```git push heroku mybranch:master```, or heroku will just silently skip pulling your submodules.

More about heroku support for submodules here: https://devcenter.heroku.com/articles/git-submodules
