### ISSUE TITLE
How to run `meteor shell` and other meteor commands on Heroku?

### ISSUE THREAD

**Issue by lpender** [AdmitHub/meteor-buildpack-horse#74]
I'd like to be able to run `meteor shell` on my heroku server.

`meteor mongo` would also be nice.

Any ideas about how one might go about doing so?

**Comment by yourcelf** [comment]
There is, unfortunately, no way to do either of these.  `meteor shell` only exists for dev environments; once the meteor app is built for deployment it doesn't exist.  I really wish it did; it would make running maintenance operations and migrations much easier.

Even more so with `meteor mongo`: That command connects to the local instance of mongodb that meteor spins up.  When you deploy to heroku, there is no local mongodb instance; mongo's running on a different server.  So your best bet is to identify the URI to your mongo instance (check the value of the environment variable `MONGOLAB_URI` if you're using mongolab), and connect to that using mongo directly.

**Comment by AndrewMagliozzi** [comment]
I like Robomongo: https://robomongo.org/
