### ISSUE TITLE
Fail to deploy 1.2.1 apps

### ISSUE THREAD

**Issue by lirbank** [AdmitHub/meteor-buildpack-horse#75]
Hi, the resent changes seems to have broken the buildpack for Meteor 1.2.1:

```
remote: Now you need to do one of the following:
remote: 
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack20160322-160-jf5jam/meteor-LQ7N/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote: 
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: cat: /tmp/build_f708209ea2383581b95e6f87f0d40dbf/.meteor/release: No such file or directory
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to ****.
remote: 
To https://git.heroku.com/****.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/****.git'
```

**Comment by lirbank** [comment]
Update, it works just fine with an older version of the pack, eg using this:

```
BUILDPACK_URL: https://github.com/AdmitHub/meteor-buildpack-horse.git#eb6bb6cdbe098183f708f47c789348c06e1b5d52
```

**Comment by lirbank** [comment]
Or actually, no, I'm still having problems. I'll keep investigating and post my findings here.

**Comment by yourcelf** [comment]
Let me know, I'll update as soon as we have some info.  The initial failure you posted looks related to the more recent commits, so maybe there's more than one problem.  Do you not have `.meteor/release` checked in with your app repo?

**Comment by yourcelf** [comment]
Are you using an iron:scaffolding setup?  looks like we may have broken that.

**Comment by yourcelf** [comment]
I just pushed a fix and confirmed that a vanilla iron scaffolding project is now working.  If you're still encountering errors please let me know.

**Comment by yourcelf** [comment]
I just pushed a fix and confirmed that a vanilla iron scaffolding project is now working.  If you're still encountering errors please let me know.

**Comment by lirbank** [comment]
Ok, I was trying with older and older versions, this one works: https://github.com/AdmitHub/meteor-buildpack-horse/commit/fb37ee8c099dbd8113c8dba2fe0a72707ca2c4f8 but not a more recent one like https://github.com/AdmitHub/meteor-buildpack-horse/commit/d46b0550c7fe4f246777f4d8d5386f26ffb3913f

I'll try the most recent version now! BRB

**Comment by yourcelf** [comment]
Please paste any errors you get here.

**Comment by lirbank** [comment]
The most recent version works like a charm. Thanks a bunch!

**Comment by lirbank** [comment]
So weird, no it's failing to deploy again (using the latest version of the buildpack). Not sure if this is has to do with the buildpack or something else though.

```
remote: fibers@1.0.5 node_modules/fibers
remote: -----> Adding PATH environment
remote: -----> Running extras
remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
remote: -----> Installing phantomjs.
remote: bzip2: (stdin) is not a bzip2 file.
remote: tar: Child returned status 2
remote: tar: Error is not recoverable: exiting now
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to ****.
remote: 
To https://git.heroku.com/****.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/****.git'
```

**Comment by lirbank** [comment]
On the third attempt it eventually worked (no changes, just retried the push to Heroku). Not sure what's going on.

**Comment by yourcelf** [comment]
bitbucket has been inconsistently available today, and we're attempting to load phantomjs from there.  The failure is that bitbucket returns something (404, 503, not sure) other than the tar.bz2 that we expect as the phantomjs distribution.  I'm not sure what we can do about that other than trying to find a more reliable distributor of phantomjs.

**Comment by lirbank** [comment]
Aha, got it! Ok, very well. Let's leave it as is. 

Side Note: I guess phantomjs is just to got the spiderable packet to work. Google has depricated the _escaped_fragment_ and recommend against using it, so I am actually considering dropping spiderable all together. Details: https://developers.google.com/webmasters/ajax-crawling/docs/faq

**Comment by yourcelf** [comment]
Good to know, thanks.  May be worth removing the default phantomjs soon then.  I opened that as #76.

**Comment by kartikTT** [comment]
FWIW, I keep getting this error as well. Sometimes it takes 4-5 pushes (~30mins -1hr) to push successfully.

**Comment by lirbank** [comment]
@kartikTT I hear ya, I also hade one today, but it worked on the second attempt. @yourcelf mention above, the error is due to bitbucket having issues. See #76 for details about dropping phantomjs all together.
