### ISSUE TITLE
Buildpack should default to appname + herokuapp.com for ROOT_URL

### ISSUE THREAD

**Issue by RobertLowe** [AdmitHub/meteor-buildpack-horse#77]
Since heroku has [Pipelines](https://devcenter.heroku.com/articles/pipelines) now and [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) are deployed automatically, it would be nice to have the buildpack to default the ROOT_URL to appname + herokuapp.com. Rather then failing to build like in #42, like all things in life the universe and everything, we should probably treat this as a default, meaning when ROOT_URL provided we use that instead.

I'll create a fork to fix this, but first I gotta eat something and maybe a nap... should have it wrapped up in a couple hours.  👍

**Comment by yourcelf** [comment]
I'm in favor of setting a default; though I'm curious if this would have any negative impact on Dokku users who use this buildpack (Dokku is a self-hosted docker-based Heroku clone -- there are a bunch of folks who use Dokku with meteor-buildpack-horse).  I expect a worst case scenario is a Dokku user gets a  herokuapp URL set in their build if they don't set `ROOT_URL` themselves, and their app will not work.

**Comment by yourcelf** [comment]
As of #90, we're now setting the default URL, but can only do so when the app name is available to the dyno.  To get that, enable [Dyno Metadata](https://devcenter.heroku.com/articles/dyno-metadata) for your app.  This is documented in the README.
