### ISSUE TITLE
Push rejected / pre-receive hook declined / failed to push some refs

### ISSUE THREAD

**Issue by brunolemos** [AdmitHub/meteor-buildpack-horse#8]
Getting this errors after trying to push any meteor project to heroku:

``` shell
remote: ----->  app detected
remote: -----> Installing node
remote: -----> Installing meteor
...
remote: -----> Compressing... done, 22.2MB
remote: -----> Launching... 
remote:  !     Push failed: error creating release
remote: Verifying deploy...
remote: !   Push rejected
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs
```

It used to work some weeks ago. Any idea?

**Comment by nspangler** [comment]
@yourcelf  I am having the same issue with Meteor 1.0.2.1.

**Comment by grp06** [comment]
@yourcelf same issue as @nspangler

**Comment by adam-bitium** [comment]
@yourcelf Likewise, in the same boat as @nspangler and @nicolaslopezj

**Comment by allpratik** [comment]
@yourcelf same issue as of @nspangler, @adam-bitium and @nicolaslopezj

**Comment by ivankravchenko** [comment]
@yourcelf same issue as @nspangler, @adam-bitium, @nicolaslopezj and @allpratik
Already working apps still working, new apps fails.
How can I help here?

**Comment by yourcelf** [comment]
Hey @ivankravchenko,

can you share some details on the setup for your new app?
 - are you using mongolab, or compose/mongohq, or something else?
 - can you provide all relevant portions of the heroku logs where it fails?
 - ideally, can you provide the source to your new app so I can do a test deploy of it?

**Comment by ivankravchenko** [comment]
Using mongolab.
Tried to deploy with and without mongolab addon added.
Added you as collaborator to [meteor-heroku-deploy-test](https://github.com/ivankravchenko/meteor-heroku-deploy-test). This is just plain fresh Meteor app after `meteor create`.
Also created `meteor-heroku-deploy-test` heroku app, can add you as collaborator if you provide email.

```
$ git push heroku master
-----> Fetching custom git buildpack... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.0.3.1 has been installed in your home directory (~/.meteor).

...

-----> Adding PATH environment
-----> Running extras
-----> Adding MONGOHQ_URL -> MONGO_URL env
-----> Adding MONGOLAB_URI -> MONGO_URL env
-----> Installing phantomjs.
-----> Discovering process types
       Procfile declares types   -> (none)
       Default types for Node.js -> web

-----> Compressing... done, 22.1MB
-----> Launching... 
 !     Push rejected, failure creating release

To git@heroku.com:meteor-heroku-deploy-test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:meteor-heroku-deploy-test.git'
```

**Comment by ivankravchenko** [comment]
Bam! I have successfully created and launched an app.
https://serene-harbor-9260.herokuapp.com/
```
$ heroku create
Creating serene-harbor-9260... done, stack is cedar-14
https://serene-harbor-9260.herokuapp.com/ | https://git.heroku.com/serene-harbor-9260.git
Git remote heroku added
$ heroku config:set BUILDPACK_URL=https://github.com/AdmitHub/meteor-buildpack-horse.git
Setting config vars and restarting serene-harbor-9260... done, v3
BUILDPACK_URL: https://github.com/AdmitHub/meteor-buildpack-horse.git
$ heroku addons:add mongolab
Adding mongolab on serene-harbor-9260... done, v4 (free)
Welcome to MongoLab.  Your new subscription is being created and will be available shortly.  Please consult the MongoLab Add-on Admin UI to check on its progress.
Use `heroku addons:docs mongolab` to view documentation.
$ heroku config:set ROOT_URL=https://serene-harbor-9260.herokuapp.com
Setting config vars and restarting serene-harbor-9260... done, v5
ROOT_URL: https://serene-harbor-9260.herokuapp.com
$ git push heroku master
Counting objects: 16, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (16/16), 2.26 KiB | 0 bytes/s, done.
Total 16 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Node.js app detected
remote: -----> Installing node
remote: -----> Installing meteor
remote: Downloading Meteor distribution
remote: ######################################################################## 100.0%
remote: 
remote: Meteor 1.0.3.1 has been installed in your home directory (~/.meteor).
remote: 
remote: Now you need to do one of the following:
remote: 
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack_3d04fdf76059542ab103ac7181b25615/meteor-mtJc/.meteor/packages/meteor-tool/1.0.40/meteor-tool-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote: 
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: -----> Bundling bundle
remote: ios: platform is not in this project
remote: android: platform is not in this project
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No description
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No README data
remote: 
remote: > fibers@1.0.1 install /tmp/build_3d04fdf76059542ab103ac7181b25615/.meteor/heroku_build/app/programs/server/node_modules/fibers
remote: > node ./build.js
remote: 
remote: `linux-x64-v8-3.14` exists; testing
remote: Binary is fine; exiting
remote: underscore@1.5.2 node_modules/underscore
remote: 
remote: eachline@2.3.3 node_modules/eachline
remote: └── type-of@2.0.1
remote: 
remote: semver@4.1.0 node_modules/semver
remote: 
remote: chalk@0.5.1 node_modules/chalk
remote: ├── escape-string-regexp@1.0.2
remote: ├── ansi-styles@1.1.0
remote: ├── supports-color@0.2.0
remote: ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
remote: └── has-ansi@0.1.0 (ansi-regex@0.2.1)
remote: 
remote: source-map-support@0.2.8 node_modules/source-map-support
remote: └── source-map@0.1.32 (amdefine@0.1.0)
remote: 
remote: fibers@1.0.1 node_modules/fibers
remote: -----> Adding PATH environment
remote: -----> Running extras
remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
remote: -----> Installing phantomjs.
remote: -----> Discovering process types
remote:        Procfile declares types   -> (none)
remote:        Default types for Node.js -> web
remote: 
remote: -----> Compressing... done, 22.1MB
remote: -----> Launching... done, v6
remote:        https://serene-harbor-9260.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/serene-harbor-9260.git
 * [new branch]      master -> master
```

**Comment by ivankravchenko** [comment]
@yourcelf 
Seems like I have detected root of a problem.
I usually using `hk` instead of `heroku` utility.
I have tried very same process, but with creating app with `hk create` and get error (after configuring and pushing). `heroku create` – ok.

**Comment by yourcelf** [comment]
Cool.  I just did these steps and it worked too:

    (create meteor-heroku-deploy-test in heroku with web based tool)
    git clone https://github.com/ivankravchenko/meteor-heroku-deploy-test.git
    cd meteor-heroku-deploy-test/
    heroku git:remote -a meteor-heroku-deploy-test
    heroku config:set BUILDPACK_URL=https://github.com/AdmitHub/meteor-buildpack-horse.git
    heroku config:set ROOT_URL=https://meteor-heroku-deploy-test.herokuapp.com
    heroku addons:add mongolab
    git push heroku master

I wonder if ``hk create`` creates an older ``cedar`` stack rather than the newer ``cedar-14`` stack?

**Comment by ivankravchenko** [comment]
`heroku create` creates `cedar-14`
`hk create` creates `cedar-14`

**Comment by yourcelf** [comment]
ok, not sure why it would be different then..  if you can identify why, please let us know so we can maybe support it in the future.

**Comment by ivankravchenko** [comment]
I have no idea too. Maybe it worth to mention this strange case in readme.

**Comment by fullhdpixel** [comment]
I've also encountered this issue. See the log here:
http://pastebin.com/raw.php?i=dxQt6tqs

**Comment by yourcelf** [comment]
@fullhdpixel From the logs it looks like the build succeeded, but launching it failed.

Check the heroku logs ("heroku logs") to see if there's anything helpful there.  Or if you're able, share the repository for the meteor app.

**Comment by fullhdpixel** [comment]
Nothing useful shows up with heroku logs (no error msgs). I can't share the code for the app, but I can assure you it works with meteor deploy. The app contains a few npm packages, which work fine on local and the meteor deploy server.

**Comment by yourcelf** [comment]
@fullhdpixel OK, tough to debug from here then.  You might check common failure points:

 - Check that mongolab addons are set up correctly, with their environment variables.
 - Check that the ROOT_URL environment variable is set correctly in heroku.

**Comment by fullhdpixel** [comment]
Ok, thank you. I will report back to you as soon as I have results.

**Comment by lirbank** [comment]
I had the same issue just now. New app created from CLI. Once I deleted the app and created it from Heroku's web UI it all worked. No clue why, but I there are no dynos when the app is created from the CLI and the web UI complains about a missing procfile.

```
$ heroku ps -a myapp
Free quota left: 17h 59m
```
vs
```
$ heroku ps -a myapp
Free quota left: 17h 55m
=== web (Free): `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
web.1: up 2015/08/14 15:53:17 (~ 5m ago)
```

**Comment by nzerobe** [comment]
It did not work for me.

**Comment by nikeshT12** [comment]
C:\django\amazon book\chapter 5 blog app>git push heroku master
Counting objects: 76, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (69/69), done.
Writing objects: 100% (76/76), 21.02 KiB | 371.00 KiB/s, done.
Total 76 (delta 24), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing python-3.6.5
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 11.8.2…
remote:        Your Pipfile.lock (98871e) is out of date. Expected: (c8cd79).
remote:        Aborting deploy.
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to powerful-savannah-99539.
remote:
To https://git.heroku.com/powerful-savannah-99539.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/powerful-savannah-99539.git'

**Comment by galymzhan91** [comment]
man, you have to set buildpacks for your heroku
$ heroku buildpacks:set heroku/nodejs

https://devcenter.heroku.com/articles/buildpacks

**Comment by AdminAbhi** [comment]
I was having the same problem,
what i did was just checked my package.json file there was SYNTAX ERROR.
That's it! I hope u got it.

**Comment by Hasneet** [comment]
I had this same issue, however none of the solutions mentioned above worked for me, I even tried to clean my remote repo, using heroku-repo plugin which by the way you can install using heroku plugins:install heroku-repo followed by heroku repo:reset -a appname to try luck with this one.

The solutions which worked for me was to disable the node_modules cache from heroku. Heroku maintains a cache directory that is persisted between builds. This cache is used to store caches for npm, yarn, and bower.

Try using the following steps.

heroku config:set NODE_MODULES_CACHE=false
now push again with - git push heroku master

**Comment by devmnj** [comment]
Nop
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/app65.git'

**Comment by SystemDZ** [comment]
Non of these solutions worked for me
 **! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/dzcommerce.git'**

**Comment by manishavalecha** [comment]
I tried everything but none worked for me , I get this error when I pushed the code to heroku

$ git push origin main
Enumerating objects: 421, done.
Counting objects: 100% (421/421), done.
Delta compression using up to 4 threads
Compressing objects: 100% (408/408), done.
Writing objects: 100% (421/421), 579.95 KiB | 2.81 MiB/s, done.
Total 421 (delta 85), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote: FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' subdirectory.  (Tried /tmp/build_5217039f)
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: ccd453da451137249e85a546ae2b50a178ed97df
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version ccd453da451137249e85a546ae2b50a178ed97df
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to fathomless-cliffs-87852.
remote:
To https://git.heroku.com/fathomless-cliffs-87852.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/fathomless-cliffs-87852.git'

**Comment by NewmorphinSwadesh** [comment]
i tried every single possible way told here and nothing happen 
now i got the bellow error and please help me if anyone have any solution

git push heroku master
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 1.04 KiB | 354.00 KiB/s, done.
Total 8 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote:  !     No default language could be detected for this app.
remote:                         HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote:                         See https://devcenter.heroku.com/articles/buildpacks
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to py3pi.
remote:
To https://git.heroku.com/py3pi.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/py3pi.git'

**Comment by Raza2468** [comment]
D:\Raza\New folder>git add . && git commit -m "initial commit" && git push heroku master
[master ff63b7b] initial commit
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 65, done.
Counting objects: 100% (65/65), done.
Delta compression using up to 12 threads
Compressing objects: 100% (53/53), done.
Writing objects: 100% (65/65), 289.65 KiB | 9.34 MiB/s, done.
Total 65 (delta 7), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Determining which buildpack to use for this app
remote:  !     No default language could be detected for this app.
remote:                         HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote:                         See https://devcenter.heroku.com/articles/buildpacks
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to sweet-website.
remote:
To https://git.heroku.com/sweet-website.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/sweet-website.git'

**Comment by OmarSalah26** [comment]
i tired to solve this problem but my app still not work

**Comment by OmarSalah26** [comment]
I solved it , 

by create runtime.txt file and put on this file python-3.7.11 as the version of python i want

app.py
 Procfile
 requirements.txt
 runtime.txt
