### ISSUE TITLE
push rejected

### ISSUE THREAD

**Issue by lifenglsf** [AdmitHub/meteor-buildpack-horse#80]
i deploy add meteor app on heroku,step by step
 http://justmeteor.com/blog/deploy-to-production-on-heroku/
deploy failed
deploy messages
E:\web\meteor_blog>git push heroku master
Counting objects: 66, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (59/59), done.
Writing objects: 100% (66/66), 20.06 KiB | 0 bytes/s, done.
Total 66 (delta 20), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpa
ck-horse.git... done
remote: -----> Node.js app detected
remote: -----> Installing node
remote: -----> Installing meteor
remote: Downloading Meteor distribution
remote: Meteor 1.3 has been installed in your home directory (~/.meteor).
remote:
remote: Now you need to do one of the following:
remote:
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack20160329-162-107hj8w/meteor-4gzW/.meteor/packa
ges/meteor-tool/1.3.0_3/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin
/meteor
remote:
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: -----> Upgrading meteor to METEOR@1.2.1
remote: Installed. Run 'meteor update --release 1.2.1' inside of a particular project
remote: directory to update that project to Meteor 1.2.1.
remote: -----> Bundling bundle
remote:
remote:
remote: While removing platforms:
remote: error: android: platform is not in this project
remote:
remote: -----> Building Meteor with ROOT_URL: https://mymeteorblog.herokuapp.com

remote: npm WARN deprecated This version of npm lacks support for important feat
ures,
remote: npm WARN deprecated such as scoped packages, offered by the primary npm
remote: npm WARN deprecated registry. Consider upgrading to at least npm@2, if n
ot the
remote: npm WARN deprecated latest stable version. To upgrade to npm@2, run:
remote: npm WARN deprecated
remote: npm WARN deprecated   npm -g install npm@latest-2
remote: npm WARN deprecated
remote: npm WARN deprecated To upgrade to the latest stable version, run:
remote: npm WARN deprecated
remote: npm WARN deprecated   npm -g install npm@latest
remote: npm WARN deprecated
remote: npm WARN deprecated (Depending on how Node.js was installed on your syst
em, you
remote: npm WARN deprecated may need to prefix the preceding commands with `sudo
`, or if
remote: npm WARN deprecated on Windows, run them from an Administrator prompt.)
remote: npm WARN deprecated
remote: npm WARN deprecated If you're running the version of npm bundled with
remote: npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of
0.10 LTS
remote: npm WARN deprecated will be bundled with a version of npm@2, which has s
ome small
remote: npm WARN deprecated backwards-incompatible changes made to `npm run-scri
pt` and
remote: npm WARN deprecated semver behavior.
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No description
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
remote: npm WARN package.json meteor-dev-bundle@0.0.0 No README data
remote:
remote: > fibers@1.0.5 install /tmp/build_ac09a3d1d94269159cb94072b196686a/.mete
or/heroku_build/app/programs/server/node_modules/fibers
remote: > node ./build.js
remote:
remote: `linux-x64-v8-3.14` exists; testing
remote: Binary is fine; exiting
remote: ansi-regex@0.2.1 node_modules/ansi-regex
remote:
remote: ansi-styles@1.1.0 node_modules/ansi-styles
remote:
remote: escape-string-regexp@1.0.3 node_modules/escape-string-regexp
remote: chalk@0.5.1 node_modules/chalk
remote:
remote: supports-color@0.2.0 node_modules/supports-color
remote:
remote: has-ansi@0.1.0 node_modules/has-ansi
remote:
remote: strip-ansi@0.3.0 node_modules/strip-ansi
remote:
remote: eachline@2.3.3 node_modules/eachline
remote:
remote: type-of@2.0.1 node_modules/type-of
remote:
remote: amdefine@1.0.0 node_modules/amdefine
remote:
remote: asap@2.0.3 node_modules/asap
remote:
remote: underscore@1.5.2 node_modules/underscore
remote: meteor-promise@0.5.0 node_modules/meteor-promise
remote:
remote: promise@7.0.4 node_modules/promise
remote:
remote: source-map-support@0.3.2 node_modules/source-map-support
remote:
remote: semver@4.1.0 node_modules/semver
remote:
remote: source-map@0.1.32 node_modules/source-map
remote:
remote: fibers@1.0.5 node_modules/fibers
remote: -----> Adding PATH environment
remote: -----> Running extras
remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
remote: -----> Installing phantomjs.
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote:
remote: -----> Compressing...
remote:        Done: 30.9M
remote: -----> Launching...
remote:  !     Please verify your account to install this add-on plan (please en
ter a credit card) For more information, see https://devcenter.heroku.com/catego
ries/billing Verify now at https://heroku.com/verify
remote:
remote:  !     Push failed due to an unrecognized error, and we've been notified
.
remote:
remote:  !     Please try pushing again.
remote:  !     If the problem persists, see http://help.heroku.com/and provide Request ID 54374b1f-d603-4ee3-bd50-f783946e5d4f.
remote:
remote:
remote: Verifying deploy....
remote:
remote: !       Push rejected to mymeteorblog.
remote:
To https://git.heroku.com/mymeteorblog.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/mymeteorblog.git'

**Comment by yourcelf** [comment]
```
 ! Please verify your account to install this add-on plan (please en
ter a credit card) For more information, see https://devcenter.heroku.com/catego
ries/billing Verify now at https://heroku.com/verify
remote:
remote: ! Push failed due to an unrecognized error, and we've been notified
```

Looks like Heroku wants you to verify your account by adding a credit card.  You could do that, or remove `mongolab`.  Fork this buildpack, and modify https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/release to remove the 'mongolab' addon.

**Comment by lifenglsf** [comment]
Oh no,i have no credit card.i try to modify source

**Comment by lifenglsf** [comment]
@yourcelf thanks.remove mongolab addon,worked.

**Comment by lifenglsf** [comment]
@yourcelf i deployed success.how can i set mongo_url,i found app run error,and needed setting mongo_url to environment

**Comment by yourcelf** [comment]
`heroku config:set MONGO_URL=<your url>`

The purpose of the mongolab addon is to be the mongodb database that runs with the app.  If you don't use mongolab via heroku, you'll need to set up whatever mongodb vendor you're using and find the URL.

**Comment by lifenglsf** [comment]
understand.chinese no credit card,unhappy
