### ISSUE TITLE
push rejected ./meteor/release no such file

### ISSUE THREAD

**Issue by jortegamo** [AdmitHub/meteor-buildpack-horse#81]
remote: Meteor 1.3 has been installed in your home directory (~/.meteor).
remote: 
remote: Now you need to do one of the following:
remote: 
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack20160329-160-33di4h/meteor-JMfZ/.meteor/packages/meteor-tool/1.3.0_3/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote: 
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: cat: /tmp/build_d74da321e0e21b6d0b2a4b6e826a48c9/.meteor/release: No such file or directory
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to duckflight.
remote: 
To https://git.heroku.com/duckflight.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/duckflight.git'

It's my first time deploying with heroku and i have this error. I need fix it quickly. Someone can help me? Thanks :)

**Comment by yourcelf** [comment]
Did you commit the `.meteor` directory in with your project?  You must, it should not be .gitignore'd.  It has its own .gitignore file within it to ignore any locally built files.

**Comment by jortegamo** [comment]
I did commit the .meteor directory. Inside this directory exists a .gitignore file. The content is: local. I should delete it?, Sorry I don`t understand. Thanks

**Comment by yourcelf** [comment]
No, do not delete `.meteor`.  There should be a file in `.meteor` called `release` which contains a version string for Meteor itself (e.g. `METEOR@1.2.1`).  This buildpack uses that file to ensure that the correct version of Meteor runs.  Do you think it's possible that you removed that file?  What version of Meteor does your app run?

**Comment by jortegamo** [comment]
Yeah, inside .meteor folder exists a file named release. I've applied cat command and result is:
METEOR@1.3

**Comment by yourcelf** [comment]
And that file is checked in to version control?  The error you're getting is when heroku downloads your app, it can't find that file.

**Comment by jortegamo** [comment]
Yes, I pushed to my origin master in github and explore to .meteor and release shows the same line: METEOR@1.3.

**Comment by yourcelf** [comment]
Is your meteor app in a subdirectory of your repository, not the top level?  e.g.

    yourrepo/
        |---- .git
        |---- somefolder/
                |----  .meteor/
                |----   server/
                |----    ...

**Comment by jortegamo** [comment]
yeah, why?

**Comment by jortegamo** [comment]
I must create a new repository into my app folder and use it to create remote for heroku?

**Comment by yourcelf** [comment]
This buildpack assumes that the project will be in the top-level, or in a folder named `app/`.  If it's anywhere else, it won't work, is why. :)  The buildpack has to know where to find your meteor app.

I recommend you fork this buildpack and change the path that it will look for the app.  See these lines:  https://github.com/AdmitHub/meteor-buildpack-horse/blob/1a75dcb47db71b549f271394d2288d131b762d1a/bin/compile#L32-L37

Change the `"app/" to the path that you use for your meteor app.  For example, if you use the path "`src/", change line 36 to:

       APP_SOURCE_DIR="$APP_SOURCE_DIR/src/"

**Comment by jortegamo** [comment]
Thanks i will try it!!

**Comment by jortegamo** [comment]
Ive tried this. The problem is in my app structure i will try to change it. Thanks!!!

**Comment by yourcelf** [comment]
Closing now, reopen if you encounter further trouble.
