### ISSUE TITLE
Meteor local server on mobile - Error: Error parsing asset manifest

### ISSUE THREAD

**Issue by rudza** [AdmitHub/meteor-buildpack-horse#85]
I have deployed a Meteor app on Heroku.

I have added a platform: Android

When I try I build the app using the `meteor build` command `meteor build --directory ~/builds --server https://my-app.herokuapp.com` and the install the apk using `adb`, I get an error.

I get the same error when trying to run app locally, but with different server: `meteor run android-device --mobile-server https://my-app.herokuapp.com`

The error is: 

    Error: Error parsing asset manifest(…)
    (anonymous function) @ webapp.js?hash=2552b0d8c8f134d5763b6897c1be6c9bfa3e9c28:68
    (anonymous function) @ webapp_local_server.js:37
    cordova.callbackFromNative @ cordova.js:293
    processMessage @ cordova.js:1081
    processMessages @ cordova.js:1104
    pollOnce @ cordova.js:973
    pollOnceFromOnlineEvent @ cordova.js:960

Here is some more information: https://forums.meteor.com/t/meteor-local-server-on-mobile-error-error-parsing-asset-manifest/21215/3

**Comment by yourcelf** [comment]
Thanks for the forum link! Very helpful.  Should be fixed in #90.
