### ISSUE TITLE
MONGO_URL needs to be set manually?

### ISSUE THREAD

**Issue by k-electron** [AdmitHub/meteor-buildpack-horse#88]
I get 'Error: MONGO_URL must be set in environment' unless i set it manually in the config vars.

**Comment by k-electron** [comment]
Although, looking at the build log:

asap@2.0.3 node_modules/asap
underscore@1.5.2 node_modules/underscore
meteor-promise@0.5.1 node_modules/meteor-promise
promise@7.0.4 node_modules/promise
source-map-support@0.3.2 node_modules/source-map-support
semver@4.1.0 node_modules/semver
source-map@0.1.32 node_modules/source-map
fibers@1.0.8 node_modules/fibers
-----> Adding PATH environment
-----> Running extras
-----> Adding MONGOHQ_URL -> MONGO_URL env
-----> Adding MONGOLAB_URI -> MONGO_URL env
-----> Installing phantomjs.
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...

**Comment by yourcelf** [comment]
Are you doing anything unusual with your setup for Mongolab (or other mongodb provider)?  One of MONGOHQ_URL, MONGOLAB_URI, or MONGO_URL needs to be set in the environment.  By default, Mongolab sets MONGOLAB_URI when its addon is installed; but if things are customized there it might not happen.

**Comment by yourcelf** [comment]
Ah, nevermind: it looks like MongoLab recently changed their variable name from MONGOLAB_URI to MONGODB_URI.  So new deployments will run into this.  Also caught by #87.

**Comment by k-electron** [comment]
doh. that solves it.

i'll wait for that to be merged in.

**Comment by yourcelf** [comment]
Fixed in #90.

**Comment by k-electron** [comment]
thx.
