### ISSUE TITLE
Application Error? (Meteor 1.3)

### ISSUE THREAD

**Issue by gg2001** [AdmitHub/meteor-buildpack-horse#89]
I am getting the Application Error when I try to push the example Todos app to heroku (https://github.com/meteor/todos.git) I am using meteor 1.3. I am following the instructions here (http://stackoverflow.com/questions/26867881/application-error-after-deploying-meteor-1-0-app-on-heroku). However, I am not doing the windows parts, as I am using a mac, and i am not doing the parts using a mongoLabgs URL, but instead a the free mongoLabs 500mb addon. The app runs fine on a local server, and when I push it to heroku, there are no errors, but I get the Application Error when I open the app (ggtodos.herokuapp.com). Why is this?
Here is the github repository: https://github.com/gg2001/GauthamTodos.git

 Here is my log:

> egaumbp:todos gg$ git push heroku master
> Counting objects: 3, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (3/3), done.
> Writing objects: 100% (3/3), 319 bytes | 0 bytes/s, done.
> Total 3 (delta 2), reused 0 (delta 0)
> remote: Git submodules detected, installing:
> remote: 
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
> remote: -----> Node.js app detected
> remote: -----> Installing node
> remote: -----> Installing meteor
> remote: Downloading Meteor distribution
> remote: ######################################################################## 100.0%
> remote: 
> remote: Meteor 1.3.1 has been installed in your home directory (~/.meteor).
> remote: 
> remote: Now you need to do one of the following:
> remote: 
> remote:   (1) Add "$HOME/.meteor" to your path, or
> remote:   (2) Run this command as root:
> remote:         cp "/tmp/buildpack20160416-160-cqvcpn/meteor-2qqX/.meteor/packages/meteor-tool/1.3.1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
> remote: 
> remote: Then to get started, take a look at 'meteor --help' or see the docs at
> remote: docs.meteor.com.
> remote: -----> Bundling bundle
> remote: npm WARN package.json ggtodos@0.0.1 No repository field.
> remote: npm WARN package.json ggtodos@0.0.1 No README data
> remote: npm WARN package.json ggtodos@0.0.1 No license field.
> remote: npm WARN engine postcss@5.0.19: wanted: {"node":">=0.12"} (current: {"node":"0.10.44","npm":"2.15.0"})
> remote: eslint-config-airbnb@6.2.0 node_modules/eslint-config-airbnb
> remote: 
> remote: eslint-plugin-react@4.3.0 node_modules/eslint-plugin-react
> remote: 
> remote: eslint@2.8.0 node_modules/eslint
> remote: ├── path-is-absolute@1.0.0
> remote: ├── imurmurhash@0.1.4
> remote: ├── path-is-inside@1.0.1
> remote: ├── pluralize@1.2.1
> remote: ├── strip-json-comments@1.0.4
> remote: ├── ignore@3.1.1
> remote: ├── progress@1.1.8
> remote: ├── estraverse@4.2.0
> remote: ├── globals@9.4.0
> remote: ├── text-table@0.2.0
> remote: ├── esutils@2.0.2
> remote: ├── user-home@2.0.0 (os-homedir@1.0.1)
> remote: ├── is-resolvable@1.0.0 (tryit@1.0.2)
> remote: ├── debug@2.2.0 (ms@0.7.1)
> remote: ├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
> remote: ├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
> remote: ├── require-uncached@1.0.2 (resolve-from@1.0.1, caller-path@0.1.0)
> remote: ├── mkdirp@0.5.1 (minimist@0.0.8)
> remote: ├── doctrine@1.2.1 (isarray@1.0.0, esutils@1.1.6)
> remote: ├── optionator@0.8.1 (fast-levenshtein@1.1.3, type-check@0.3.2, deep-is@0.1.3, levn@0.3.0, wordwrap@1.0.0, prelude-ls@1.1.2)
> remote: ├── glob@7.0.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
> remote: ├── shelljs@0.6.0
> remote: ├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
> remote: ├── is-my-json-valid@2.13.1 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
> remote: ├── inquirer@0.12.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, figures@1.5.0, ansi-escapes@1.3.0, through@2.3.8, cli-width@2.1.0, run-async@0.1.0, readline2@1.0.1, string-width@1.0.1, cli-cursor@1.0.2, rx-lite@3.1.2)
> remote: ├── file-entry-cache@1.2.4 (object-assign@4.0.1, flat-cache@1.0.10)
> remote: ├── js-yaml@3.6.0 (esprima@2.7.2, argparse@1.0.7)
> remote: ├── espree@3.1.3 (acorn@3.0.4, acorn-jsx@2.0.1)
> remote: ├── table@3.7.8 (slice-ansi@0.0.4, strip-ansi@3.0.1, tv4@1.2.7, string-width@1.0.1, xregexp@3.1.0, bluebird@3.3.5)
> remote: ├── es6-map@0.1.3 (d@0.1.1, es6-symbol@3.0.2, event-emitter@0.3.4, es6-iterator@2.0.0, es6-set@0.1.4, es5-ext@0.10.11)
> remote: ├── escope@3.6.0 (esrecurse@4.1.0, es6-weak-map@2.0.1)
> remote: └── lodash@4.11.1
> remote: 
> remote: eslint-plugin-meteor@3.4.0 node_modules/eslint-plugin-meteor
> remote: ├── lodash.memoize@4.0.1 (lodash._mapcache@4.1.5)
> remote: ├── path-exists@2.1.0 (pinkie-promise@2.0.1)
> remote: ├── invariant@2.2.1 (loose-envify@1.1.0)
> remote: ├── lodash.find@4.2.0 (lodash._basefindindex@3.6.0, lodash._basefind@3.0.0, lodash._baseeach@4.1.2, lodash._baseiteratee@4.6.1)
> remote: ├── escope@3.6.0 (estraverse@4.2.0, esrecurse@4.1.0, es6-weak-map@2.0.1, es6-map@0.1.3)
> remote: ├── babel-register@6.7.2 (path-exists@1.0.0, home-or-tmp@1.0.0, mkdirp@0.5.1, source-map-support@0.2.10, babel-core@6.7.6, lodash@3.10.1, babel-runtime@5.8.38, core-js@2.2.2)
> remote: ├── babel-polyfill@6.7.2 (babel-regenerator-runtime@6.5.0, babel-runtime@5.8.38, core-js@2.2.2)
> remote: └── babel-runtime@6.6.1 (core-js@2.2.2)
> remote: 
> remote: autoprefixer@6.3.4 node_modules/autoprefixer
> remote: ├── normalize-range@0.1.2
> remote: ├── num2fraction@1.2.2
> remote: ├── postcss-value-parser@3.3.0
> remote: ├── browserslist@1.3.0
> remote: ├── postcss@5.0.19 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.3)
> remote: └── caniuse-db@1.0.30000436
> remote: 
> remote: faker@3.1.0 node_modules/faker
> remote: android: removed platform
> remote: -----> Building Meteor with ROOT_URL: http://ggtodos.herokuapp.com
> remote: Currently, it is only possible to build iOS apps on an OS X system.
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No description
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> remote: npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
> remote: 
> remote: > fibers@1.0.8 install /tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers
> remote: > node build.js || nodejs build.js
> remote: 
> remote: make: Entering directory `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/build'
> remote:   CXX(target) Release/obj.target/fibers/src/fibers.o
> remote:   CXX(target) Release/obj.target/fibers/src/coroutine.o
> remote:   CC(target) Release/obj.target/fibers/src/libcoro/coro.o
> remote:   SOLINK_MODULE(target) Release/obj.target/fibers.node
> remote:   COPY Release/fibers.node
> remote: make: Leaving directory `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/build'
> remote: Installed in `/tmp/build_d048f968b0572d516eb3253c8594edc0/.meteor/heroku_build/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
> remote: ansi-regex@0.2.1 node_modules/ansi-regex
> remote: 
> remote: ansi-styles@1.1.0 node_modules/ansi-styles
> remote: 
> remote: escape-string-regexp@1.0.5 node_modules/escape-string-regexp
> remote: 
> remote: has-ansi@0.1.0 node_modules/has-ansi
> remote: 
> remote: strip-ansi@0.3.0 node_modules/strip-ansi
> remote: 
> remote: supports-color@0.2.0 node_modules/supports-color
> remote: 
> remote: chalk@0.5.1 node_modules/chalk
> remote: 
> remote: eachline@2.3.3 node_modules/eachline
> remote: 
> remote: type-of@2.0.1 node_modules/type-of
> remote: 
> remote: amdefine@1.0.0 node_modules/amdefine
> remote: 
> remote: asap@2.0.3 node_modules/asap
> remote: 
> remote: underscore@1.5.2 node_modules/underscore
> remote: 
> remote: meteor-promise@0.5.1 node_modules/meteor-promise
> remote: 
> remote: promise@7.0.4 node_modules/promise
> remote: 
> remote: source-map-support@0.3.2 node_modules/source-map-support
> remote: 
> remote: semver@4.1.0 node_modules/semver
> remote: 
> remote: source-map@0.1.32 node_modules/source-map
> remote: 
> remote: fibers@1.0.8 node_modules/fibers
> remote: -----> Adding PATH environment
> remote: -----> Running extras
> remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
> remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
> remote: -----> Installing phantomjs.
> remote: 
> remote: -----> Discovering process types
> remote:        Procfile declares types     -> (none)
> remote:        Default types for buildpack -> web
> remote: 
> remote: -----> Compressing...
> remote:        Done: 97.2M
> remote: -----> Launching...
> remote:        Released v12
> remote:        https://ggtodos.herokuapp.com/ deployed to Heroku
> remote: 
> remote: Verifying deploy... done.
> To https://git.heroku.com/ggtodos.git
>    87427cb..e8558d3  master -> master

**Comment by yourcelf** [comment]
Can you look at heroku's logs and see if there's anything helpful there?  Type this from your project root:

    heroku logs

the `-t` flag will follow the logs.

**Comment by jhuenges** [comment]
@yourcelf  I have the same problem. Here is my log. It seems to be a problem with MONGO_URL

```
2016-04-16T15:26:49.022830+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-04-16T15:26:52.549684+00:00 app[web.1]:
2016-04-16T15:26:52.549799+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
2016-04-16T15:26:52.550130+00:00 app[web.1]:                                            throw(ex);
2016-04-16T15:26:52.550155+00:00 app[web.1]:                                                  ^
2016-04-16T15:26:52.897039+00:00 app[web.1]: Error: MONGO_URL must be set in environment
2016-04-16T15:26:52.897058+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
2016-04-16T15:26:52.897059+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2016-04-16T15:26:52.897060+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
2016-04-16T15:26:52.897061+00:00 app[web.1]:     at meteorInstall.imports.api.persons.persons.js (imports/api/persons/persons.js:5:24)
2016-04-16T15:26:52.897062+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
2016-04-16T15:26:52.897062+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
2016-04-16T15:26:52.897064+00:00 app[web.1]:     at meteorInstall.imports.startup.server.fixtures.js (imports/startup/server/fixtures.js:1:1)
2016-04-16T15:26:52.897064+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
2016-04-16T15:26:52.897065+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
2016-04-16T15:26:52.897065+00:00 app[web.1]:     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:2:1)
2016-04-16T15:26:53.787969+00:00 heroku[web.1]: Process exited with status 8
2016-04-16T15:26:53.806576+00:00 heroku[web.1]: State changed from starting to crashed
2016-04-16T15:26:53.807540+00:00 heroku[web.1]: State changed from crashed to starting
2016-04-16T15:26:58.938379+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-04-16T15:27:01.890687+00:00 app[web.1]:
2016-04-16T15:27:01.890816+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
2016-04-16T15:27:01.891201+00:00 app[web.1]:                                            throw(ex);
2016-04-16T15:27:01.891210+00:00 app[web.1]:                                                  ^
2016-04-16T15:27:02.181170+00:00 app[web.1]: Error: MONGO_URL must be set in environment
2016-04-16T15:27:02.181183+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
2016-04-16T15:27:02.181185+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2016-04-16T15:27:02.181186+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
2016-04-16T15:27:02.181186+00:00 app[web.1]:     at meteorInstall.imports.api.persons.persons.js (imports/api/persons/persons.js:5:24)
2016-04-16T15:27:02.181187+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
2016-04-16T15:27:02.181188+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
2016-04-16T15:27:02.181189+00:00 app[web.1]:     at meteorInstall.imports.startup.server.fixtures.js (imports/startup/server/fixtures.js:1:1)
2016-04-16T15:27:02.181189+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
2016-04-16T15:27:02.181190+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
2016-04-16T15:27:02.181191+00:00 app[web.1]:     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:2:1)
2016-04-16T15:27:03.078257+00:00 heroku[web.1]: Process exited with status 8
2016-04-16T15:27:03.095968+00:00 heroku[web.1]: State changed from starting to crashed
2016-04-16T15:27:04.446228+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pure-chamber-52973.herokuapp.com reques
t_id=9ea744d1-9d8b-47cb-95dc-cfbc3fcc2202 fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
2016-04-16T15:27:05.800049+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=pure-chamber-52973.herokuapp
.com request_id=b9f47f5a-8ecd-4c59-9aa2-6cf61dbd288d fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
2016-04-16T15:27:27.359296+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pure-chamber-52973.herokuapp.com reques
t_id=cf420f7a-364f-42fc-b852-eeb8346f7d96 fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
2016-04-16T15:27:28.503038+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=pure-chamber-52973.herokuapp
.com request_id=66e84216-cf65-4d53-a697-d0145fb0e607 fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
```

**Comment by jhuenges** [comment]
@yourcelf I solved my problem by adding a new config variable (`MONGO_URL`) through the dashboard.

**Comment by yourcelf** [comment]
The buildpack includes extras to set the values of MONGOHQ_URL or MONGOLAB_URI to MONGO_URL, but if none of the three are defined, you'll get this problem.  This is probably a result of the way you're using the free MongoLab addon distinct from the default one.

We should add a section to the README that explains different Mongo configurations, as this comes out a fair bit.

**Comment by yourcelf** [comment]
Fixed in #90.

**Comment by gg2001** [comment]
Here are the Heroku Logs:
Is there any way to fix this issue?

> 2016-04-16T09:08:07.303259+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ggtodos.herokuapp.com request_id=12ecab05-4119-4cc0-a6ca-254855b32839 fwd="60.97.35.115" dyno= connect= service= status=503 bytes=
> 2016-04-16T09:08:08.764819+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ggtodos.herokuapp.com request_id=d17bf512-78f8-4587-934a-57666be968f1 fwd="60.97.35.115" dyno= connect= service= status=503 bytes=
> 2016-04-16T09:22:32.628989+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-04-16T09:22:43.409826+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
> 2016-04-16T09:22:47.022746+00:00 app[web.1]: 
> 2016-04-16T09:22:47.022842+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
> 2016-04-16T09:22:47.023076+00:00 app[web.1]: 					throw(ex);
> 2016-04-16T09:22:47.023092+00:00 app[web.1]: 					      ^
> 2016-04-16T09:22:47.350740+00:00 app[web.1]: Error: MONGO_URL must be set in environment
> 2016-04-16T09:22:47.350749+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
> 2016-04-16T09:22:47.350750+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
> 2016-04-16T09:22:47.350751+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
> 2016-04-16T09:22:47.350752+00:00 app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
> 2016-04-16T09:22:47.350752+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
> 2016-04-16T09:22:47.350753+00:00 app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
> 2016-04-16T09:22:47.350754+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
> 2016-04-16T09:22:47.350754+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
> 2016-04-16T09:22:47.350755+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1889:15
> 2016-04-16T09:22:47.350756+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1900:3
> 2016-04-16T09:22:48.351433+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-04-16T09:22:48.336429+00:00 heroku[web.1]: Process exited with status 8
> 2016-04-16T10:05:46.768554+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-04-16T10:05:56.733172+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
> 2016-04-16T10:06:00.103604+00:00 app[web.1]: 
> 2016-04-16T10:06:00.103707+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
> 2016-04-16T10:06:00.103912+00:00 app[web.1]: 					throw(ex);
> 2016-04-16T10:06:00.103923+00:00 app[web.1]: 					      ^
> 2016-04-16T10:06:00.288517+00:00 app[web.1]: Error: MONGO_URL must be set in environment
> 2016-04-16T10:06:00.288528+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
> 2016-04-16T10:06:00.288530+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
> 2016-04-16T10:06:00.288529+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
> 2016-04-16T10:06:00.288536+00:00 app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
> 2016-04-16T10:06:00.288537+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
> 2016-04-16T10:06:00.288543+00:00 app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
> 2016-04-16T10:06:00.288549+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
> 2016-04-16T10:06:00.288550+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
> 2016-04-16T10:06:00.288550+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1889:15
> 2016-04-16T10:06:00.288551+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1900:3
> 2016-04-16T10:06:01.119228+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-04-16T10:06:01.108739+00:00 heroku[web.1]: Process exited with status 8
> 2016-04-16T11:35:42.073993+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-04-16T11:35:52.400041+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
> 2016-04-16T11:35:55.679819+00:00 app[web.1]: 
> 2016-04-16T11:35:55.680049+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
> 2016-04-16T11:35:55.680488+00:00 app[web.1]: 					throw(ex);
> 2016-04-16T11:35:55.680623+00:00 app[web.1]: 					      ^
> 2016-04-16T11:35:55.979179+00:00 app[web.1]: Error: MONGO_URL must be set in environment
> 2016-04-16T11:35:55.979189+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
> 2016-04-16T11:35:55.979189+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
> 2016-04-16T11:35:55.979190+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
> 2016-04-16T11:35:55.979191+00:00 app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
> 2016-04-16T11:35:55.979192+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
> 2016-04-16T11:35:55.979193+00:00 app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
> 2016-04-16T11:35:55.979193+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
> 2016-04-16T11:35:55.979194+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
> 2016-04-16T11:35:55.979195+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1889:15
> 2016-04-16T11:35:55.979195+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1900:3
> 2016-04-16T11:35:56.935357+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-04-16T11:35:56.920464+00:00 heroku[web.1]: Process exited with status 8
> 2016-04-16T11:45:45.873966+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ggtodos.herokuapp.com request_id=f1012136-b4d5-40bd-b4ba-8bc9abd65d6d fwd="60.97.35.115" dyno= connect= service= status=503 bytes=
> 2016-04-16T11:45:50.300446+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ggtodos.herokuapp.com request_id=921c9ef6-ed28-4ece-9a6b-e6436f40284d fwd="60.97.35.115" dyno= connect= service= status=503 bytes=
> 2016-04-16T14:24:46.175601+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-04-16T14:25:00.410987+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
> 2016-04-16T14:25:05.087857+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
> 2016-04-16T14:25:05.088102+00:00 app[web.1]: 					      ^
> 2016-04-16T14:25:05.087692+00:00 app[web.1]: 
> 2016-04-16T14:25:05.088087+00:00 app[web.1]: 					throw(ex);
> 2016-04-16T14:25:05.495210+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
> 2016-04-16T14:25:05.495152+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
> 2016-04-16T14:25:05.495153+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
> 2016-04-16T14:25:05.495141+00:00 app[web.1]: Error: MONGO_URL must be set in environment
> 2016-04-16T14:25:05.495216+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1900:3
> 2016-04-16T14:25:05.495214+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
> 2016-04-16T14:25:05.495215+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1889:15
> 2016-04-16T14:25:05.495214+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
> 2016-04-16T14:25:05.495213+00:00 app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
> 2016-04-16T14:25:05.495211+00:00 app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
> 2016-04-16T14:25:05.495212+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
> 2016-04-16T14:25:06.569356+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-04-16T14:25:06.548756+00:00 heroku[web.1]: Process exited with status 8
> 2016-04-16T15:06:36.540723+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ggtodos.herokuapp.com request_id=0f5b2ef7-4a7b-42fe-ba31-a6b76d6795aa fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
> 2016-04-16T15:06:37.154783+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ggtodos.herokuapp.com request_id=3bfe9f66-713c-4d71-8233-198d8b8f4fe4 fwd="95.90.234.152" dyno= connect= service= status=503 bytes=
> 2016-04-16T19:58:05.209390+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-04-16T19:58:17.856301+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
> 2016-04-16T19:58:20.988468+00:00 app[web.1]: 					throw(ex);
> 2016-04-16T19:58:20.988471+00:00 app[web.1]: 					      ^
> 2016-04-16T19:58:21.174087+00:00 app[web.1]: Error: MONGO_URL must be set in environment
> 2016-04-16T19:58:21.174104+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
> 2016-04-16T19:58:21.174105+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
> 2016-04-16T19:58:20.988223+00:00 app[web.1]: 
> 2016-04-16T19:58:21.174113+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
> 2016-04-16T19:58:21.174118+00:00 app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
> 2016-04-16T19:58:21.174112+00:00 app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
> 2016-04-16T19:58:20.988267+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
> 2016-04-16T19:58:21.174123+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:158:9)
> 2016-04-16T19:58:21.174124+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1889:15
> 2016-04-16T19:58:21.174123+00:00 app[web.1]:     at require (packages/modules-runtime.js:92:16)
> 2016-04-16T19:58:21.174106+00:00 app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:102:40)
> 2016-04-16T19:58:21.174124+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/accounts-base.js:1900:3
> 2016-04-16T19:58:21.876147+00:00 heroku[web.1]: Process exited with status 8
> 2016-04-16T19:58:21.875210+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by jhuenges** [comment]
@gg2001 you could use the new version of the buildpack or change the mongo url manually
