### ISSUE TITLE
Consider removing mongolab from `bin/release`, or making it optional

### ISSUE THREAD

**Issue by Pushplaybang** [AdmitHub/meteor-buildpack-horse#95]
I'm using mongolab, but not keen on verifying my heroku account and interested to see how I would make this work.  

I set `MONGO_URL` and removed the mongolab var, but when doing a build I get the following 👍 

```
remote: -----> Launching...
remote:  !     Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify
remote:
remote:  !     Push failed due to an unrecognized error, and we've been notified.
```

I'm assuming the unrecognised error is the error immediately above it.

**Comment by Pushplaybang** [comment]
just found issue #43  which explains this, I'm going to go ahead and create my own fork.  I wonder if this could be optional in the buildpack?

**Comment by yourcelf** [comment]
I think we could make it optional.  Two thoughts on this:

 - The "addons" are [only created on first run of the buildpack](https://devcenter.heroku.com/articles/buildpack-api#bin-release) on a particular heroku app. We already give instructions in the README for people to explicitly add mongolab, so for people following those directions, the declaration in `bin/release` may be redundant.
 - While it's a bit of a pain, we could read environment variables in to `bin/release` and look for something that suppresses adding mongolab.  Here's how we do this in [`bin/compile`](https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L12-L24).

I'm going to reopen this for us to think on and consider it.

**Comment by Pushplaybang** [comment]
ok great, yeah simply removing the addon got it working from my fork, would be great to have this as an option  👍 .

**Comment by AdamBrodzinski** [comment]
I had to fork as well, using mongolab is not needed for me. Making mongolab opt-in would be great.

**Comment by Pushplaybang** [comment]
Yeah I'm using compose.io for production apps, though I suspect that there's nothing more than the addons,

**Comment by yourcelf** [comment]
The beta version of meteor-buildpack-horse removes the mongolab addon from `bin/release`.  You can still have mongolab if you add it explicitly with `heroku addons:create mongolab` when setting up the app in the first place (which the usage instructions have always suggested).  This should make it easier to use other mongodb providers without having to fork.

You can try it now with:
```
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git
```

**Comment by yourcelf** [comment]
Mongolab is now removed by default from `bin/release` in the master branch.
