### ISSUE TITLE
Images not loaded in mobile app but shown in 

### ISSUE THREAD

**Issue by rubenlpz** [AdmitHub/meteor-buildpack-horse#98]
This is a strange issue: Images are not loaded in the mobile app but they are properly shown in the browser site.  The images of my app are loaded from the web and not from files, linking to a url in html   *img src="https://domain/image-sample.jpg"*.

What I have test:

Running the app locally:
Using a browser: (localhost:3000).  Result: Ok, images are shown.
Using a mobile  (Deployed via USB with Meteor run androd-device).   Result: Ok, images are shown.

Hosting the app in Heroku server: 
Using a browser (mobile browser : https://tags12.herokuapp.com  Result: Ok, Images are shown.
Using a mobile (Deployed meteor app): ERROR: No images shown, no error displayed.     
Using the mobile browser:  Result: Ok, Images are shown.

Any advice what could be happening?

**Comment by yourcelf** [comment]
Are the images served under http:// (not secure) while the deployed site is https:// (secure) ?  Different browsers have different defaults for displaying insecure content on a secure site.

**Comment by rubenlpz** [comment]
Thanks, I found the solution.  You need to add a line in your mobile-config.js (file should be located in the root of your meteor folder) to allow load resources from other URLs.   This is the line:

_   App.accessRule("*");_   
// this allow any url to be loaded.  If you want an specific url, change the "*" with the domain to allow, by example www.facebook.com
