### ISSUE TITLE
On new 1.3 apps, error when pushing to Heroku

### ISSUE THREAD

**Issue by sturoid** [AdmitHub/meteor-buildpack-horse#99]
Hi there. I have been using the buidpack on a 1.2 app that is being converted to 1.3 and it is working great. I have now created some new 1.3 apps and I get this error whenever I try to deploy:

remote: build: You're not in a Meteor project directory.
remote:
remote: To create a new Meteor project:
remote:   meteor create <project name>
remote: For example:
remote:   meteor create myapp

Am I missing something simple here? Any help is much appreciated and thanks again for your time and work.

**Comment by Cristo-Conklin** [comment]
Ensure that your git project root is top level, not inside a subfolder

Em 08/05/2016 05:39, "Stuart Clove" <notifications@github.com> escreveu:
>
> Hi there. I have been using the buidpack on a 1.2 app that is being
converted to 1.3 and it is working great. I have now created some new 1.3
apps and I get this error whenever I try to deploy:
>
> remote: build: You're not in a Meteor project directory.
> remote:
> remote: To create a new Meteor project:
> remote: meteor create
> remote: For example:
> remote: meteor create myapp
>
> Am I missing something simple here? Any help is much appreciated and
thanks again for your time and work.

**Comment by sturoid** [comment]
Here is a screenshot of my project folder. I think everything is right as far as the .git folder and everything.

<img width="723" alt="screen shot 2016-05-08 at 11 19 01 am" src="https://cloud.githubusercontent.com/assets/805554/15099294/cafef184-150e-11e6-9a72-1fda119b3bcf.png">

**Comment by yourcelf** [comment]
@sturoid can you share code for a project that exhibits this failure?  Or failing that, the contents of your `.gitignore` file?

**Comment by sturoid** [comment]
Hi @yourcelf. Thank again and again for your help. Here are the listing for the code base and the .gitignore. Does that help?

<img width="979" alt="screen shot 2016-05-08 at 1 59 09 pm" src="https://cloud.githubusercontent.com/assets/805554/15100083/38a8c7a8-1525-11e6-9e4f-9b22e7fa84ed.png">
<img width="598" alt="screen shot 2016-05-08 at 1 59 26 pm" src="https://cloud.githubusercontent.com/assets/805554/15100084/38a911d6-1525-11e6-95d6-504b3bb882c4.png">

**Comment by yourcelf** [comment]
Try removing `packages` from .gitignore.  In general, the `packages/` directory should not be gitignored; but further, having that general entry will exclude the `.meteor/packages` file which could be causing the issue.

**Comment by sturoid** [comment]
You are a hero. That was the issue. Sorry for the dumb mistake and thank you again.
